/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package FrontendBancopoly;

import Casillas.Casilla;
import java.io.Serializable;
import javax.swing.*;

/**
 *
 * @author phily
 */
public class CustomizacionTodasTarjetasDeUnTipo extends javax.swing.JDialog implements Serializable {
    Casilla casillaFisica;
    
    /**
     * Creates new form CustomizacionMoverA
     */
    public CustomizacionTodasTarjetasDeUnTipo(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }
    
    public void establecerTItuloSegunCasilla(int tipoCasilla){
        switch(tipoCasilla){
            case 0:
                lbl_titulo.setText("CAMINAR");
                lbl_cantidad.setText("# Pasos");                
            break;
                
           case 1:
               lbl_titulo.setText("PREMIO");
               lbl_cantidad.setText("Efectivo $:");
            break;
                
            case 2:
                lbl_titulo.setText("MOVER A");                
                lbl_cantidad.setText("# Casilla");
            break;
                
            case 3:
                lbl_titulo.setText("RETROCEDER");
                lbl_cantidad.setText("# Pasos");
            break;
                
            case 4:
                lbl_titulo.setText("PAGAR A TODOS");                
                lbl_cantidad.setText("Cantidad $");
            break;
                
           case 5:
               lbl_titulo.setText("MULTA");
                lbl_cantidad.setText("Pago $");
            break;
               
           case 6:
               lbl_titulo.setText("PÉRDIDA DE TURNOS");
                lbl_cantidad.setText("Cantidad :");
            break;    
                
           case 7:
               lbl_titulo.setText("VAYA A LA CÁRCEL");
               lbl_cantidad.setText("# turnos");
            break;    
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lbl_titulo = new javax.swing.JLabel();
        Spn_numeroCasilla = new javax.swing.JSpinner();
        lbl_cantidad = new javax.swing.JLabel();
        lbl_descripcion = new javax.swing.JLabel();
        txtF_breveDescripcion = new javax.swing.JTextField();
        btn_aceptar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(400, 300));
        setMinimumSize(new java.awt.Dimension(400, 300));
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(99, 94, 87));
        jPanel1.setMaximumSize(new java.awt.Dimension(400, 300));
        jPanel1.setMinimumSize(new java.awt.Dimension(400, 300));

        lbl_titulo.setBackground(new java.awt.Color(218, 214, 210));
        lbl_titulo.setFont(new java.awt.Font("Sawasdee", 1, 20)); // NOI18N
        lbl_titulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_titulo.setText(" ");
        lbl_titulo.setOpaque(true);

        Spn_numeroCasilla.setModel(new javax.swing.SpinnerNumberModel());

        lbl_cantidad.setFont(new java.awt.Font("Sawasdee", 0, 15)); // NOI18N
        lbl_cantidad.setForeground(new java.awt.Color(220, 211, 211));
        lbl_cantidad.setText("# Casilla :");

        lbl_descripcion.setFont(new java.awt.Font("Sawasdee", 0, 15)); // NOI18N
        lbl_descripcion.setForeground(new java.awt.Color(220, 211, 211));
        lbl_descripcion.setText("Breve descripción:");

        txtF_breveDescripcion.setText(" ");

        btn_aceptar.setText("ACEPTAR");
        btn_aceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_aceptarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbl_titulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(79, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lbl_descripcion)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtF_breveDescripcion))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lbl_cantidad)
                                .addGap(60, 60, 60)
                                .addComponent(Spn_numeroCasilla, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(79, 79, 79))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(btn_aceptar)
                        .addGap(40, 40, 40))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(lbl_titulo)
                .addGap(50, 50, 50)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_cantidad)
                    .addComponent(Spn_numeroCasilla, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_descripcion)
                    .addComponent(txtF_breveDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                .addComponent(btn_aceptar)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_aceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_aceptarActionPerformed
            this.dispose();
    }//GEN-LAST:event_btn_aceptarActionPerformed

    public void establecerRangoSpinner(){//pues para avanzar ya se tien el if que controa todo esto.. y para mover a no hay que definir nada puesto que es un cpompuesto de retroceder y avanzar
        /*switch(tipoCasilla){
            case 0://caminar
             Spn_numeroCasilla.setModel(new javax.swing.SpinnerNumberModel(0, 0, casilla-1, 1));//tendría que ser el número de la última casilla -1, el total de casillas que podrá caminar sin problema alguno
            break;
            
            case 2://mover a
             Spn_numeroCasilla.setModel(new javax.swing.SpinnerNumberModel(0, 0, casilla-1, 1));//tendrían que ser todos los índices hasta el último, pero exceptuando en el que se encuentra esta casilla... eso aún no se como hacerlo
            break;//deberá agarrarse el último índice en el momento en el que se presione listo
            
            case 3://retroceder  
             Spn_numeroCasilla.setModel(new javax.swing.SpinnerNumberModel(0, 0, casilla-1, 1));//no se xD, min, max, paso
            break;
        }*/
        
        Spn_numeroCasilla.setModel(new javax.swing.SpinnerNumberModel(0, 0, casillaFisica.obtnerIndiceRecorrido()-1, 1));
        
    }
    
    public int entregarCasillaAIr(){
        return (Integer) Spn_numeroCasilla.getValue();
    }
    
    public String entregarDefinicion(){
        return txtF_breveDescripcion.getText();
    }
    
    public void recibirCasillFisica(Casilla casilla){
        casillaFisica=casilla;
    }
    
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSpinner Spn_numeroCasilla;
    private javax.swing.JButton btn_aceptar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbl_cantidad;
    private javax.swing.JLabel lbl_descripcion;
    private javax.swing.JLabel lbl_titulo;
    private javax.swing.JTextField txtF_breveDescripcion;
    // End of variables declaration//GEN-END:variables
}
