/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package FrontendBancopoly;

import RegistroYManejoTemporalDatos.RegistroTemporalDatosPartida;
import java.awt.event.ItemEvent;
import java.awt.event.ItemListener;
import javax.swing.JButton;
import javax.swing.JCheckBox;
import javax.swing.JComboBox;
import javax.swing.JDialog;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JOptionPane;


/**
 *
 * @author phily
 */
public class CustomizacionCasillasEficiente extends javax.swing.JDialog {        
        RegistroTemporalDatosPartida registroTemporal = new RegistroTemporalDatosPartida();
    
        JPanel panelPrincipal = new JPanel(); 
        private int cantidadInicios=0;
    /**
     * Creates new form CustomizacionCasillasEficiente
     */
    public CustomizacionCasillasEficiente(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        JPn_Trampa.setVisible(false);
        JPn_construccionesLugar.setVisible(false);
        JPn_propiedadesGenerales.setVisible(false);
        JPn_tomarTarjeta.setVisible(false);
        addPanelPrincipalCompleto();      
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLayeredPane1 = new javax.swing.JLayeredPane();
        JPn_construccionesLugar = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lbl_simpleConstruccion = new javax.swing.JLabel();
        lbl_SofisticadaConstruccion = new javax.swing.JLabel();
        FtxtF_contruccSImple = new javax.swing.JFormattedTextField();
        FtxtF_construccSofisticada = new javax.swing.JFormattedTextField();
        btn_AceptarPropiedades = new javax.swing.JButton();
        btn_regresarPropiedades = new javax.swing.JButton();
        JPn_propiedadesGenerales = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtF_nuevoGrupo = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        cbBx_GruposExistentes = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        txtF_nombreLugar = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        FtxtF_pagoEstancia = new javax.swing.JFormattedTextField();
        jLabel7 = new javax.swing.JLabel();
        FtxtF_pagoHIpoteca = new javax.swing.JFormattedTextField();
        btn_aceptarServicioEstacion = new javax.swing.JButton();
        btn_siguienteConstrucciones = new javax.swing.JButton();
        JPn_Trampa = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        FtxtF_cdadTrampa = new javax.swing.JFormattedTextField();
        jLabel11 = new javax.swing.JLabel();
        txtF_descripcionTRampa = new javax.swing.JTextField();
        btn_aceptarTrampa = new javax.swing.JButton();
        JPn_tomarTarjeta = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        txtF_breveDescripcion = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox<>();
        chkBx_caminar = new javax.swing.JCheckBox();
        chkBx_retroceder = new javax.swing.JCheckBox();
        chkBx_Multa = new javax.swing.JCheckBox();
        ckBx_Premio = new javax.swing.JCheckBox();
        chkBx_moverA = new javax.swing.JCheckBox();
        chkBx_PagarA = new javax.swing.JCheckBox();
        chkBx_PerderTurno = new javax.swing.JCheckBox();
        chkBx_irCarcel = new javax.swing.JCheckBox();
        chkBx_Personalizada = new javax.swing.JCheckBox();
        jLabel15 = new javax.swing.JLabel();
        chkBx_SalirCarcel = new javax.swing.JCheckBox();
        Spn_numeroRepeticiones = new javax.swing.JSpinner();
        btn_aceptarTarjeta = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        JPn_construccionesLugar.setBackground(new java.awt.Color(115, 111, 106));

        jLabel1.setBackground(new java.awt.Color(241, 214, 187));
        jLabel1.setFont(new java.awt.Font("Sawasdee", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(23, 7, 7));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("<<CONSTRUCCIONES>>");
        jLabel1.setOpaque(true);

        lbl_simpleConstruccion.setForeground(new java.awt.Color(215, 203, 203));
        lbl_simpleConstruccion.setText("Precio por cada :");

        lbl_SofisticadaConstruccion.setForeground(new java.awt.Color(215, 203, 203));
        lbl_SofisticadaConstruccion.setText("Precio por cada :");

        FtxtF_contruccSImple.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));

        FtxtF_construccSofisticada.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));

        btn_AceptarPropiedades.setText("ACEPTAR");
        btn_AceptarPropiedades.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_AceptarPropiedadesActionPerformed(evt);
            }
        });

        btn_regresarPropiedades.setText("<");

        javax.swing.GroupLayout JPn_construccionesLugarLayout = new javax.swing.GroupLayout(JPn_construccionesLugar);
        JPn_construccionesLugar.setLayout(JPn_construccionesLugarLayout);
        JPn_construccionesLugarLayout.setHorizontalGroup(
            JPn_construccionesLugarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPn_construccionesLugarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btn_regresarPropiedades, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49)
                .addGroup(JPn_construccionesLugarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(JPn_construccionesLugarLayout.createSequentialGroup()
                        .addComponent(lbl_SofisticadaConstruccion)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 112, Short.MAX_VALUE)
                        .addComponent(FtxtF_construccSofisticada, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(JPn_construccionesLugarLayout.createSequentialGroup()
                        .addComponent(lbl_simpleConstruccion)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(FtxtF_contruccSImple, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(100, 100, 100))
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JPn_construccionesLugarLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_AceptarPropiedades)
                .addGap(46, 46, 46))
        );
        JPn_construccionesLugarLayout.setVerticalGroup(
            JPn_construccionesLugarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPn_construccionesLugarLayout.createSequentialGroup()
                .addGap(112, 112, 112)
                .addComponent(jLabel1)
                .addGroup(JPn_construccionesLugarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(JPn_construccionesLugarLayout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addGroup(JPn_construccionesLugarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl_simpleConstruccion)
                            .addComponent(FtxtF_contruccSImple, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(JPn_construccionesLugarLayout.createSequentialGroup()
                        .addGap(74, 74, 74)
                        .addComponent(btn_regresarPropiedades)))
                .addGap(8, 8, 8)
                .addGroup(JPn_construccionesLugarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(FtxtF_construccSofisticada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_SofisticadaConstruccion))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 146, Short.MAX_VALUE)
                .addComponent(btn_AceptarPropiedades)
                .addGap(24, 24, 24))
        );

        JPn_propiedadesGenerales.setBackground(new java.awt.Color(143, 139, 134));
        JPn_propiedadesGenerales.setMaximumSize(new java.awt.Dimension(511, 483));
        JPn_propiedadesGenerales.setMinimumSize(new java.awt.Dimension(511, 483));

        jLabel2.setBackground(new java.awt.Color(247, 173, 99));
        jLabel2.setFont(new java.awt.Font("Sawasdee", 1, 18)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("<<PROPIEDADES>>");
        jLabel2.setOpaque(true);

        jLabel3.setForeground(new java.awt.Color(230, 218, 218));
        jLabel3.setText("Nuevo grupo: ");

        txtF_nuevoGrupo.setText(" ");

        jLabel4.setForeground(new java.awt.Color(230, 218, 218));
        jLabel4.setText("Grupos Existentes:");

        jLabel5.setForeground(new java.awt.Color(230, 218, 218));
        jLabel5.setText("Nombre del lugar :");

        txtF_nombreLugar.setText(" ");

        jLabel6.setForeground(new java.awt.Color(230, 218, 218));
        jLabel6.setText("Pago por estancia :");

        FtxtF_pagoEstancia.setText(" ");

        jLabel7.setForeground(new java.awt.Color(230, 218, 218));
        jLabel7.setText("Pago por hipoteca :");

        FtxtF_pagoHIpoteca.setText(" ");

        btn_aceptarServicioEstacion.setText("ACEPTAR");
        btn_aceptarServicioEstacion.setEnabled(false);
        btn_aceptarServicioEstacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_aceptarServicioEstacionActionPerformed(evt);
            }
        });

        btn_siguienteConstrucciones.setText(">");
        btn_siguienteConstrucciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_siguienteConstruccionesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout JPn_propiedadesGeneralesLayout = new javax.swing.GroupLayout(JPn_propiedadesGenerales);
        JPn_propiedadesGenerales.setLayout(JPn_propiedadesGeneralesLayout);
        JPn_propiedadesGeneralesLayout.setHorizontalGroup(
            JPn_propiedadesGeneralesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(JPn_propiedadesGeneralesLayout.createSequentialGroup()
                .addGroup(JPn_propiedadesGeneralesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(JPn_propiedadesGeneralesLayout.createSequentialGroup()
                        .addGap(74, 74, 74)
                        .addGroup(JPn_propiedadesGeneralesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(JPn_propiedadesGeneralesLayout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cbBx_GruposExistentes, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(JPn_propiedadesGeneralesLayout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(30, 30, 30)
                                .addComponent(txtF_nuevoGrupo))
                            .addGroup(JPn_propiedadesGeneralesLayout.createSequentialGroup()
                                .addGap(28, 28, 28)
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtF_nombreLugar, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                        .addComponent(btn_siguienteConstrucciones, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(JPn_propiedadesGeneralesLayout.createSequentialGroup()
                        .addGap(143, 143, 143)
                        .addGroup(JPn_propiedadesGeneralesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addGroup(JPn_propiedadesGeneralesLayout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(28, 28, 28)
                                .addGroup(JPn_propiedadesGeneralesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(FtxtF_pagoHIpoteca, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(FtxtF_pagoEstancia, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(JPn_propiedadesGeneralesLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_aceptarServicioEstacion)
                        .addGap(45, 45, 45)))
                .addContainerGap())
        );
        JPn_propiedadesGeneralesLayout.setVerticalGroup(
            JPn_propiedadesGeneralesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPn_propiedadesGeneralesLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel2)
                .addGap(35, 35, 35)
                .addGroup(JPn_propiedadesGeneralesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtF_nuevoGrupo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(JPn_propiedadesGeneralesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(cbBx_GruposExistentes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addGroup(JPn_propiedadesGeneralesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtF_nombreLugar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_siguienteConstrucciones))
                .addGap(47, 47, 47)
                .addGroup(JPn_propiedadesGeneralesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(FtxtF_pagoEstancia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(18, 18, 18)
                .addGroup(JPn_propiedadesGeneralesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(FtxtF_pagoHIpoteca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 55, Short.MAX_VALUE)
                .addComponent(btn_aceptarServicioEstacion)
                .addGap(23, 23, 23))
        );

        JPn_Trampa.setBackground(new java.awt.Color(146, 139, 131));

        jLabel8.setBackground(new java.awt.Color(247, 121, 69));
        jLabel8.setFont(new java.awt.Font("Sawasdee", 1, 18)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("<<TRAMPA>>");
        jLabel8.setOpaque(true);

        jLabel9.setForeground(new java.awt.Color(232, 223, 223));
        jLabel9.setText("Tipo de trampa :");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pago a otros", "Pérdida de turno", "Mover a Casilla" }));

        jLabel10.setForeground(new java.awt.Color(231, 224, 224));
        jLabel10.setText("Cantidad :");

        FtxtF_cdadTrampa.setText(" ");

        jLabel11.setForeground(new java.awt.Color(222, 213, 213));
        jLabel11.setText("Breve descripción :");

        txtF_descripcionTRampa.setText("no te pases de los bordes");

        btn_aceptarTrampa.setText("ACEPTAR");
        btn_aceptarTrampa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_aceptarTrampaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout JPn_TrampaLayout = new javax.swing.GroupLayout(JPn_Trampa);
        JPn_Trampa.setLayout(JPn_TrampaLayout);
        JPn_TrampaLayout.setHorizontalGroup(
            JPn_TrampaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(JPn_TrampaLayout.createSequentialGroup()
                .addGap(83, 83, 83)
                .addGroup(JPn_TrampaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(JPn_TrampaLayout.createSequentialGroup()
                        .addGroup(JPn_TrampaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel10)
                            .addComponent(jLabel9))
                        .addGap(39, 39, 39)
                        .addGroup(JPn_TrampaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(FtxtF_cdadTrampa, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(JPn_TrampaLayout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addGap(18, 18, 18)
                        .addComponent(txtF_descripcionTRampa)))
                .addContainerGap(93, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JPn_TrampaLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_aceptarTrampa)
                .addGap(40, 40, 40))
        );
        JPn_TrampaLayout.setVerticalGroup(
            JPn_TrampaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPn_TrampaLayout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(jLabel8)
                .addGap(105, 105, 105)
                .addGroup(JPn_TrampaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addGap(21, 21, 21)
                .addGroup(JPn_TrampaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(FtxtF_cdadTrampa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addGap(28, 28, 28)
                .addGroup(JPn_TrampaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(txtF_descripcionTRampa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 117, Short.MAX_VALUE)
                .addComponent(btn_aceptarTrampa)
                .addGap(22, 22, 22))
        );

        JPn_tomarTarjeta.setBackground(new java.awt.Color(151, 144, 134));
        JPn_tomarTarjeta.setMaximumSize(new java.awt.Dimension(511, 483));
        JPn_tomarTarjeta.setMinimumSize(new java.awt.Dimension(511, 483));

        jLabel12.setBackground(new java.awt.Color(243, 223, 165));
        jLabel12.setFont(new java.awt.Font("Sawasdee", 1, 18)); // NOI18N
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("<<TOMAR TARJETA>>");
        jLabel12.setOpaque(true);

        jLabel13.setForeground(new java.awt.Color(217, 210, 210));
        jLabel13.setText("Breve descripción :");

        txtF_breveDescripcion.setText(" ");

        jLabel14.setForeground(new java.awt.Color(206, 196, 196));
        jLabel14.setText("Tipo de tarjetas a mostrar :");

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Beneficiosa", "Maliciosa", "Variada" }));

        chkBx_caminar.setForeground(new java.awt.Color(221, 210, 210));
        chkBx_caminar.setText("Caminar");

        chkBx_retroceder.setForeground(new java.awt.Color(221, 210, 210));
        chkBx_retroceder.setText("Retroceder");

        chkBx_Multa.setForeground(new java.awt.Color(221, 210, 210));
        chkBx_Multa.setText("Multa");

        ckBx_Premio.setForeground(new java.awt.Color(221, 210, 210));
        ckBx_Premio.setText("Premio");

        chkBx_moverA.setForeground(new java.awt.Color(221, 210, 210));
        chkBx_moverA.setText("Mover a casilla");
        chkBx_moverA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkBx_moverAActionPerformed(evt);
            }
        });

        chkBx_PagarA.setForeground(new java.awt.Color(221, 210, 210));
        chkBx_PagarA.setText("Pagar a los demás");

        chkBx_PerderTurno.setForeground(new java.awt.Color(221, 210, 210));
        chkBx_PerderTurno.setText("Perder turno[s]");

        chkBx_irCarcel.setForeground(new java.awt.Color(221, 210, 210));
        chkBx_irCarcel.setText("Ir a la cárcel");

        chkBx_Personalizada.setForeground(new java.awt.Color(221, 210, 210));
        chkBx_Personalizada.setText("Personalizada");

        jLabel15.setForeground(new java.awt.Color(221, 210, 210));
        jLabel15.setText("Cantidad por cada una :");

        chkBx_SalirCarcel.setForeground(new java.awt.Color(221, 210, 210));
        chkBx_SalirCarcel.setText("Salga de la cárcel");

        Spn_numeroRepeticiones.setModel(new javax.swing.SpinnerNumberModel(1, 1, 10, 1));

        btn_aceptarTarjeta.setText("ACEPTAR");
        btn_aceptarTarjeta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_aceptarTarjetaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout JPn_tomarTarjetaLayout = new javax.swing.GroupLayout(JPn_tomarTarjeta);
        JPn_tomarTarjeta.setLayout(JPn_tomarTarjetaLayout);
        JPn_tomarTarjetaLayout.setHorizontalGroup(
            JPn_tomarTarjetaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(JPn_tomarTarjetaLayout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addGroup(JPn_tomarTarjetaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(JPn_tomarTarjetaLayout.createSequentialGroup()
                        .addGroup(JPn_tomarTarjetaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(JPn_tomarTarjetaLayout.createSequentialGroup()
                                .addGap(40, 40, 40)
                                .addGroup(JPn_tomarTarjetaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(JPn_tomarTarjetaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(JPn_tomarTarjetaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(chkBx_Multa)
                                            .addComponent(chkBx_irCarcel))
                                        .addComponent(chkBx_caminar, javax.swing.GroupLayout.Alignment.LEADING))
                                    .addComponent(chkBx_SalirCarcel)
                                    .addComponent(chkBx_retroceder)))
                            .addComponent(jLabel15))
                        .addGap(36, 36, 36)
                        .addGroup(JPn_tomarTarjetaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(JPn_tomarTarjetaLayout.createSequentialGroup()
                                .addGap(0, 125, Short.MAX_VALUE)
                                .addComponent(btn_aceptarTarjeta))
                            .addComponent(chkBx_PerderTurno)
                            .addComponent(ckBx_Premio)
                            .addComponent(chkBx_moverA)
                            .addComponent(chkBx_PagarA)
                            .addComponent(chkBx_Personalizada)))
                    .addGroup(JPn_tomarTarjetaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(JPn_tomarTarjetaLayout.createSequentialGroup()
                            .addComponent(jLabel13)
                            .addGap(31, 31, 31)
                            .addComponent(txtF_breveDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JPn_tomarTarjetaLayout.createSequentialGroup()
                            .addComponent(jLabel14)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(JPn_tomarTarjetaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(Spn_numeroRepeticiones, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(22, 22, 22))
        );
        JPn_tomarTarjetaLayout.setVerticalGroup(
            JPn_tomarTarjetaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPn_tomarTarjetaLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(jLabel12)
                .addGap(23, 23, 23)
                .addGroup(JPn_tomarTarjetaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(txtF_breveDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(JPn_tomarTarjetaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(JPn_tomarTarjetaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chkBx_caminar)
                    .addComponent(ckBx_Premio))
                .addGap(18, 18, 18)
                .addGroup(JPn_tomarTarjetaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chkBx_SalirCarcel)
                    .addComponent(chkBx_moverA))
                .addGap(28, 28, 28)
                .addGroup(JPn_tomarTarjetaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chkBx_retroceder)
                    .addComponent(chkBx_PagarA))
                .addGap(18, 18, 18)
                .addGroup(JPn_tomarTarjetaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chkBx_Multa)
                    .addComponent(chkBx_PerderTurno))
                .addGap(18, 18, 18)
                .addGroup(JPn_tomarTarjetaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chkBx_irCarcel)
                    .addComponent(chkBx_Personalizada))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addGroup(JPn_tomarTarjetaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(Spn_numeroRepeticiones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_aceptarTarjeta))
                .addGap(16, 16, 16))
        );

        jLayeredPane1.setLayer(JPn_construccionesLugar, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(JPn_propiedadesGenerales, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(JPn_Trampa, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(JPn_tomarTarjeta, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
        jLayeredPane1.setLayout(jLayeredPane1Layout);
        jLayeredPane1Layout.setHorizontalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(JPn_construccionesLugar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(JPn_propiedadesGenerales, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(JPn_Trampa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(JPn_tomarTarjeta, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jLayeredPane1Layout.setVerticalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(JPn_construccionesLugar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(JPn_propiedadesGenerales, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(JPn_Trampa, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(JPn_tomarTarjeta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_aceptarServicioEstacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_aceptarServicioEstacionActionPerformed
        
        //this.setVisible(false);//creo que estaba aquí por el hecho del comentario de más abajito en este método
        JPn_propiedadesGenerales.setVisible(false);
        JPn_construccionesLugar.setVisible(true);//te falta especificar si en el ckBx es ser o est entonces no sucederá el cambio de pantallla... además recuerda que tienes el botoncito para avanzar por cta propia
        //registroTemporal.recopilarDatosCasillasPropiedad(txtF_nuevoGrupo.getText(), txtF_nombreLugar.getText(), Integer.parseInt(FtxtF_pagoEstancia.getText()));        
        
    }//GEN-LAST:event_btn_aceptarServicioEstacionActionPerformed

    private void chkBx_moverAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkBx_moverAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chkBx_moverAActionPerformed

    private void btn_aceptarTarjetaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_aceptarTarjetaActionPerformed
        CustomizacionTarjetas dialogoTarjetas = new CustomizacionTarjetas(new javax.swing.JFrame(), true);
        dialogoTarjetas.setVisible(true);
    }//GEN-LAST:event_btn_aceptarTarjetaActionPerformed

    private void btn_AceptarPropiedadesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_AceptarPropiedadesActionPerformed
      
    }//GEN-LAST:event_btn_AceptarPropiedadesActionPerformed

    private void btn_aceptarTrampaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_aceptarTrampaActionPerformed
        panelPrincipal.setVisible(false);
        
       //registroTemporal.recopilarDatosCasillasTrampa(,,Integer.parseInt(FtxtF_cdadTrampa.getText()));//Aun te faltan los argu
    }//GEN-LAST:event_btn_aceptarTrampaActionPerformed

    private void btn_siguienteConstruccionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_siguienteConstruccionesActionPerformed
        setVisible(false);
        registroTemporal.recopilarDatosCasillasPropLugar(Integer.parseInt(FtxtF_contruccSImple.getText()), Integer.parseInt(FtxtF_construccSofisticada.getText()));
    }//GEN-LAST:event_btn_siguienteConstruccionesActionPerformed

   private void addPanelPrincipalCompleto(){
        String listadoTIposGrupo[] ={"Inicio", "Trampa","Lugar", "Servicio básico", "Estación", "Toma una tarjeta"};                    
        
         panelPrincipal.setLayout(null);
         JLabel label= new JLabel("Tipo de Grupo :");
         JButton btn_aceptarTipoCasilla = new JButton(">");
         JComboBox cbBx_tiposGrupo = new JComboBox(listadoTIposGrupo);
         
         panelPrincipal.setSize(getWidth(), getHeight());
         panelPrincipal.setBackground(new java.awt.Color(151, 144, 134));
                  
         btn_aceptarTipoCasilla.setBounds(panelPrincipal.getWidth()-100, (panelPrincipal.getHeight()-70), 40, 30);
         btn_aceptarTipoCasilla.setFont(new java.awt.Font("Sawasdee", 1, 18));
         btn_aceptarTipoCasilla.addMouseListener(new java.awt.event.MouseAdapter() {
                public void mouseClicked(java.awt.event.MouseEvent evt) {                        
                        accederAPanelSegunOPcion(cbBx_tiposGrupo);                        
                }
         });
         
         label.setBounds(100,(panelPrincipal.getHeight()/2)-50,getWidth(), 20);
         label.setForeground(new java.awt.Color(221, 210, 210));
         label.setFont(new java.awt.Font("Sawasdee", 1, 18));
         
         cbBx_tiposGrupo.setMaximumRowCount(listadoTIposGrupo.length);
         cbBx_tiposGrupo.setBounds(panelPrincipal.getWidth()-270, (panelPrincipal.getHeight()/2)-50, 170, 30);
         cbBx_tiposGrupo.addItemListener(new ItemListener(){
                  public void itemStateChanged( ItemEvent evento ){
                  // determina si está seleccionada la casilla de verificación
                        if ( evento.getStateChange() == ItemEvent.SELECTED )
                            if(cbBx_tiposGrupo.getSelectedIndex()==5){
                                    cantidadInicios+=1;
                            }
                    } // fin del método itemStateChanged
         });
         
         panelPrincipal.add(label);
         panelPrincipal.add(cbBx_tiposGrupo);
         panelPrincipal.add(btn_aceptarTipoCasilla);         
         panelPrincipal.updateUI();
        panelPrincipal.setVisible(true);
        add(panelPrincipal);
                 
   }
   
   public void accederAPanelSegunOPcion(JComboBox cbBx_tiposGrupo){//teines que arreglar la muestra de los paneles...!
       panelPrincipal.setVisible(false);
       
         if(cbBx_tiposGrupo.getSelectedIndex()==0){
                if(cantidadInicios>1){
                       JOptionPane.showInputDialog("No puede existir más de un inicio en la un mismo tablero");
                 }
                  else if(cantidadInicios==1 && cbBx_tiposGrupo.getSelectedIndex()==0){
                           
                           //panelPrincipal.setVisible(false);
                                       //Aquí se mandará a crear el objeto casilla, pues eso estabamos pensando y modificaba la casilla entonces que se destruya y add el nuevo obj.. pero eso depende de como vayas a definir el recorrido
                                       //pues si creas un método que lo detecte bien después de haber generado el mapa, entonces la lista enlazada de los obj casilla, se hará al finalizar el mapa
                                       //sino entonces si deberá hacerse conforme se vaya creando, eso sí advierte que según el orden en que vaya creando así será el recorrido... aunque
                                       //si te quieres ahorrar el método que pensará como crear el recorrido, podrías pedir que al final deslize el mouse según vaya a ser el recorrido, esto al finalizar la creación/edición
                                       //o al inicio, solicitar que seleccione las casillas a emplear en el orden que quiere se va a realizar el recorrido y que estas cambien de color y solo ahí se pueda editar, pero eso implica revisar
                                       //que lo haga seún las manecillas del reloj
                }                                                                
       }
                        
       if(cbBx_tiposGrupo.getSelectedIndex()==1){                   
                JPn_propiedadesGenerales.setVisible(false);
                 JPn_tomarTarjeta.setVisible(false);
                 JPn_Trampa.setVisible(true);                 
        }
        if(cbBx_tiposGrupo.getSelectedIndex()==2){
                 JPn_propiedadesGenerales.getComponent(11).setVisible(false);
                   JPn_Trampa.setVisible(false);                 
                 JPn_tomarTarjeta.setVisible(false);
                JPn_propiedadesGenerales.setVisible(true);
        }
        if(cbBx_tiposGrupo.getSelectedIndex()==3){
               JPn_propiedadesGenerales.getComponent(12).setVisible(false);
                 JPn_Trampa.setVisible(false);                 
                 JPn_tomarTarjeta.setVisible(false);
                JPn_propiedadesGenerales.setVisible(true);
        }
        if(cbBx_tiposGrupo.getSelectedIndex()==4){
               JPn_propiedadesGenerales.getComponent(12).setVisible(false);
                 JPn_Trampa.setVisible(false);                 
                 JPn_tomarTarjeta.setVisible(false);
                JPn_propiedadesGenerales.setVisible(true);
        }
        else{
                 JPn_Trampa.setVisible(false);
                 JPn_propiedadesGenerales.setVisible(false);                 
                 JPn_tomarTarjeta.setVisible(true);                                                  
        }
   }
   
   
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFormattedTextField FtxtF_cdadTrampa;
    private javax.swing.JFormattedTextField FtxtF_construccSofisticada;
    private javax.swing.JFormattedTextField FtxtF_contruccSImple;
    private javax.swing.JFormattedTextField FtxtF_pagoEstancia;
    private javax.swing.JFormattedTextField FtxtF_pagoHIpoteca;
    private javax.swing.JPanel JPn_Trampa;
    private javax.swing.JPanel JPn_construccionesLugar;
    private javax.swing.JPanel JPn_propiedadesGenerales;
    private javax.swing.JPanel JPn_tomarTarjeta;
    private javax.swing.JSpinner Spn_numeroRepeticiones;
    private javax.swing.JButton btn_AceptarPropiedades;
    private javax.swing.JButton btn_aceptarServicioEstacion;
    private javax.swing.JButton btn_aceptarTarjeta;
    private javax.swing.JButton btn_aceptarTrampa;
    private javax.swing.JButton btn_regresarPropiedades;
    private javax.swing.JButton btn_siguienteConstrucciones;
    private javax.swing.JComboBox<String> cbBx_GruposExistentes;
    private javax.swing.JCheckBox chkBx_Multa;
    private javax.swing.JCheckBox chkBx_PagarA;
    private javax.swing.JCheckBox chkBx_PerderTurno;
    private javax.swing.JCheckBox chkBx_Personalizada;
    private javax.swing.JCheckBox chkBx_SalirCarcel;
    private javax.swing.JCheckBox chkBx_caminar;
    private javax.swing.JCheckBox chkBx_irCarcel;
    private javax.swing.JCheckBox chkBx_moverA;
    private javax.swing.JCheckBox chkBx_retroceder;
    private javax.swing.JCheckBox ckBx_Premio;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JLabel lbl_SofisticadaConstruccion;
    private javax.swing.JLabel lbl_simpleConstruccion;
    private javax.swing.JTextField txtF_breveDescripcion;
    private javax.swing.JTextField txtF_descripcionTRampa;
    private javax.swing.JTextField txtF_nombreLugar;
    private javax.swing.JTextField txtF_nuevoGrupo;
    // End of variables declaration//GEN-END:variables
}
