/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package FrontendBancopoly;

/**
 *
 * @author phily
 */
public class CustomizacionTarjetas extends javax.swing.JDialog {

    /**
     * Creates new form CustomizacionTarjetas
     */
    public CustomizacionTarjetas(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtA_DescripciónTarjeta = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        lbl_CantidadFIja = new javax.swing.JLabel();
        JFtxt_numeroFIjo = new javax.swing.JFormattedTextField();
        lbl_CantidadCambiante = new javax.swing.JLabel();
        Ftxtf_CantidadCambiante = new javax.swing.JFormattedTextField();
        jLabel3 = new javax.swing.JLabel();
        ckbx_esCaminar = new javax.swing.JCheckBox();
        ckbx_esPremiar = new javax.swing.JCheckBox();
        ckbx_esMoverA = new javax.swing.JCheckBox();
        ckbx_esMultar = new javax.swing.JCheckBox();
        ckbx_esPagarAOtros = new javax.swing.JCheckBox();
        ckbx_esPerderTurno = new javax.swing.JCheckBox();
        jPanel3 = new javax.swing.JPanel();
        btn_anterior = new javax.swing.JButton();
        btn_Siguiente = new javax.swing.JButton();
        btn_GuardarTodo = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(193, 200, 196));

        jPanel2.setPreferredSize(new java.awt.Dimension(221, 264));

        jLabel1.setFont(new java.awt.Font("Sawasdee", 0, 15)); // NOI18N
        jLabel1.setText("jLabel1");

        txtA_DescripciónTarjeta.setColumns(10);
        txtA_DescripciónTarjeta.setRows(5);
        txtA_DescripciónTarjeta.setText("\nIngresa aquí la despcrición\n\n->Intenta no pasarte de los\n     bordes, para tener una \n     mejor vista : ]");
        txtA_DescripciónTarjeta.setPreferredSize(new java.awt.Dimension(130, 90));
        jScrollPane1.setViewportView(txtA_DescripciónTarjeta);

        jLabel2.setText(" ");

        lbl_CantidadFIja.setText("jLabel4");

        JFtxt_numeroFIjo.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        JFtxt_numeroFIjo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JFtxt_numeroFIjoActionPerformed(evt);
            }
        });

        lbl_CantidadCambiante.setText("jLabel5");
        lbl_CantidadCambiante.setEnabled(false);

        Ftxtf_CantidadCambiante.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        Ftxtf_CantidadCambiante.setEnabled(false);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbl_CantidadCambiante, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lbl_CantidadFIja, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(34, 34, 34)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(JFtxt_numeroFIjo, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                                    .addComponent(Ftxtf_CantidadCambiante))
                                .addGap(57, 57, 57)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(83, 83, 83)
                        .addComponent(jLabel1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2)
                        .addGap(29, 29, 29))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl_CantidadFIja)
                            .addComponent(JFtxt_numeroFIjo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl_CantidadCambiante)
                            .addComponent(Ftxtf_CantidadCambiante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        jLabel3.setFont(new java.awt.Font("Sawasdee", 1, 18)); // NOI18N
        jLabel3.setText("<<CUSTOMIZACIÓN DE TARJETAS>>");

        ckbx_esCaminar.setFont(new java.awt.Font("Sawasdee", 0, 15)); // NOI18N
        ckbx_esCaminar.setText("Caminar");
        ckbx_esCaminar.setEnabled(false);

        ckbx_esPremiar.setFont(new java.awt.Font("Sawasdee", 0, 15)); // NOI18N
        ckbx_esPremiar.setText("Premio monetario");
        ckbx_esPremiar.setEnabled(false);

        ckbx_esMoverA.setFont(new java.awt.Font("Sawasdee", 0, 15)); // NOI18N
        ckbx_esMoverA.setText("Mover a casilla");
        ckbx_esMoverA.setEnabled(false);

        ckbx_esMultar.setFont(new java.awt.Font("Sawasdee", 0, 15)); // NOI18N
        ckbx_esMultar.setText("Multa");
        ckbx_esMultar.setEnabled(false);

        ckbx_esPagarAOtros.setFont(new java.awt.Font("Sawasdee", 0, 15)); // NOI18N
        ckbx_esPagarAOtros.setText("Pago a jugadores");
        ckbx_esPagarAOtros.setEnabled(false);

        ckbx_esPerderTurno.setFont(new java.awt.Font("Sawasdee", 0, 15)); // NOI18N
        ckbx_esPerderTurno.setText("Perder turno(s)");
        ckbx_esPerderTurno.setEnabled(false);

        jPanel3.setBackground(new java.awt.Color(242, 236, 220));

        btn_anterior.setText("ANTERIOR");
        btn_anterior.setEnabled(false);

        btn_Siguiente.setText("SIGUIENTE");

        btn_GuardarTodo.setText("GUARDAR TODO");
        btn_GuardarTodo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_GuardarTodoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_GuardarTodo)
                .addGap(91, 91, 91)
                .addComponent(btn_anterior)
                .addGap(29, 29, 29)
                .addComponent(btn_Siguiente)
                .addGap(64, 64, 64))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(24, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_anterior)
                    .addComponent(btn_Siguiente)
                    .addComponent(btn_GuardarTodo))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(116, 116, 116)
                .addComponent(jLabel3)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ckbx_esCaminar)
                    .addComponent(ckbx_esPremiar)
                    .addComponent(ckbx_esMoverA)
                    .addComponent(ckbx_esMultar)
                    .addComponent(ckbx_esPagarAOtros)
                    .addComponent(ckbx_esPerderTurno))
                .addGap(65, 65, 65))
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel3)
                .addGap(44, 44, 44)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(ckbx_esCaminar)
                        .addGap(18, 18, 18)
                        .addComponent(ckbx_esPremiar)
                        .addGap(18, 18, 18)
                        .addComponent(ckbx_esMoverA)
                        .addGap(18, 18, 18)
                        .addComponent(ckbx_esMultar)
                        .addGap(18, 18, 18)
                        .addComponent(ckbx_esPagarAOtros)
                        .addGap(18, 18, 18)
                        .addComponent(ckbx_esPerderTurno))
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 53, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JFtxt_numeroFIjoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JFtxt_numeroFIjoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JFtxt_numeroFIjoActionPerformed

    private void btn_GuardarTodoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_GuardarTodoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_GuardarTodoActionPerformed

   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFormattedTextField Ftxtf_CantidadCambiante;
    private javax.swing.JFormattedTextField JFtxt_numeroFIjo;
    private javax.swing.JButton btn_GuardarTodo;
    private javax.swing.JButton btn_Siguiente;
    private javax.swing.JButton btn_anterior;
    private javax.swing.JCheckBox ckbx_esCaminar;
    private javax.swing.JCheckBox ckbx_esMoverA;
    private javax.swing.JCheckBox ckbx_esMultar;
    private javax.swing.JCheckBox ckbx_esPagarAOtros;
    private javax.swing.JCheckBox ckbx_esPerderTurno;
    private javax.swing.JCheckBox ckbx_esPremiar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbl_CantidadCambiante;
    private javax.swing.JLabel lbl_CantidadFIja;
    private javax.swing.JTextArea txtA_DescripciónTarjeta;
    // End of variables declaration//GEN-END:variables
}
