/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package FrontendBancopoly;

/**
 *
 * @author phily
 */
public class CustomizacionCnstrcs extends javax.swing.JDialog {

    /**
     * Creates new form CustomizacionCnstrcs
     */
    public CustomizacionCnstrcs(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JPn_construccionesLugar = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lbl_simpleConstruccion = new javax.swing.JLabel();
        lbl_SofisticadaConstruccion = new javax.swing.JLabel();
        FtxtF_contruccSImple = new javax.swing.JFormattedTextField();
        FtxtF_construccSofisticada = new javax.swing.JFormattedTextField();
        btn_AceptarPropiedades = new javax.swing.JButton();
        btn_regresarPropiedades = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(511, 483));
        setMinimumSize(new java.awt.Dimension(511, 483));
        setResizable(false);

        JPn_construccionesLugar.setBackground(new java.awt.Color(115, 111, 106));
        JPn_construccionesLugar.setMaximumSize(new java.awt.Dimension(511, 483));
        JPn_construccionesLugar.setMinimumSize(new java.awt.Dimension(511, 483));
        JPn_construccionesLugar.setPreferredSize(new java.awt.Dimension(511, 483));

        jLabel1.setBackground(new java.awt.Color(241, 214, 187));
        jLabel1.setFont(new java.awt.Font("Sawasdee", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(23, 7, 7));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("<<CONSTRUCCIONES>>");
        jLabel1.setOpaque(true);

        lbl_simpleConstruccion.setForeground(new java.awt.Color(215, 203, 203));
        lbl_simpleConstruccion.setText("Precio por cada :");

        lbl_SofisticadaConstruccion.setForeground(new java.awt.Color(215, 203, 203));
        lbl_SofisticadaConstruccion.setText("Precio por cada :");

        FtxtF_contruccSImple.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));

        FtxtF_construccSofisticada.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));

        btn_AceptarPropiedades.setText("ACEPTAR");
        btn_AceptarPropiedades.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_AceptarPropiedadesActionPerformed(evt);
            }
        });

        btn_regresarPropiedades.setText("<");

        javax.swing.GroupLayout JPn_construccionesLugarLayout = new javax.swing.GroupLayout(JPn_construccionesLugar);
        JPn_construccionesLugar.setLayout(JPn_construccionesLugarLayout);
        JPn_construccionesLugarLayout.setHorizontalGroup(
            JPn_construccionesLugarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPn_construccionesLugarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btn_regresarPropiedades, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 70, Short.MAX_VALUE)
                .addGroup(JPn_construccionesLugarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lbl_SofisticadaConstruccion)
                    .addComponent(lbl_simpleConstruccion))
                .addGap(91, 91, 91)
                .addGroup(JPn_construccionesLugarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(FtxtF_contruccSImple, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(FtxtF_construccSofisticada, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(100, 100, 100))
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JPn_construccionesLugarLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_AceptarPropiedades)
                .addGap(54, 54, 54))
        );
        JPn_construccionesLugarLayout.setVerticalGroup(
            JPn_construccionesLugarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPn_construccionesLugarLayout.createSequentialGroup()
                .addGap(112, 112, 112)
                .addComponent(jLabel1)
                .addGroup(JPn_construccionesLugarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(JPn_construccionesLugarLayout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addGroup(JPn_construccionesLugarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl_simpleConstruccion)
                            .addComponent(FtxtF_contruccSImple, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(JPn_construccionesLugarLayout.createSequentialGroup()
                        .addGap(74, 74, 74)
                        .addComponent(btn_regresarPropiedades)))
                .addGap(8, 8, 8)
                .addGroup(JPn_construccionesLugarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(FtxtF_construccSofisticada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_SofisticadaConstruccion))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 125, Short.MAX_VALUE)
                .addComponent(btn_AceptarPropiedades)
                .addGap(45, 45, 45))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(JPn_construccionesLugar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(JPn_construccionesLugar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_AceptarPropiedadesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_AceptarPropiedadesActionPerformed
        this.dispose();
    }//GEN-LAST:event_btn_AceptarPropiedadesActionPerformed

   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFormattedTextField FtxtF_construccSofisticada;
    private javax.swing.JFormattedTextField FtxtF_contruccSImple;
    private javax.swing.JPanel JPn_construccionesLugar;
    private javax.swing.JButton btn_AceptarPropiedades;
    private javax.swing.JButton btn_regresarPropiedades;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lbl_SofisticadaConstruccion;
    private javax.swing.JLabel lbl_simpleConstruccion;
    // End of variables declaration//GEN-END:variables
}
