/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package FrontendBancopoly;

import java.io.Serializable;
import javax.swing.*;

/**
 *
 * @author phily
 */
public class CustomizacionPersonalizada extends javax.swing.JDialog implements Serializable{
    boolean tarjetasFusionadas[] = new boolean[8];    
    private int cantidadSeleccionados;
    private boolean permisoParaIrCarcel=true;
    int numeroCasilla;
    
    /**
     * Creates new form customizacionPersonalizada
     */
    public CustomizacionPersonalizada(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        btnGroup_tarjeta1 = new javax.swing.ButtonGroup();
        btnGroup_tarjeta2 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        Rbtn_Premio = new javax.swing.JRadioButton();
        Rbtn_Caminar = new javax.swing.JRadioButton();
        Rbtn_moverA = new javax.swing.JRadioButton();
        Rbtn_vayaCarcel = new javax.swing.JRadioButton();
        Rbtn_multa = new javax.swing.JRadioButton();
        Rbtn_retroceder = new javax.swing.JRadioButton();
        Rbtn_pagoATodos = new javax.swing.JRadioButton();
        Rbtn_perderTurnos = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();
        txt_descripcion = new javax.swing.JTextField();
        btn_Aceptar = new javax.swing.JButton();
        Spn_tarjeta1 = new javax.swing.JSpinner();
        lbl_cantidadTarjeta1 = new javax.swing.JLabel();
        lbl_cantidadTarjeta2 = new javax.swing.JLabel();
        Spn_tarjeta2 = new javax.swing.JSpinner();
        jSeparator1 = new javax.swing.JSeparator();
        Tbtn_aceptar = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(481, 436));
        setMinimumSize(new java.awt.Dimension(481, 436));
        setResizable(false);
        getContentPane().setLayout(new java.awt.GridBagLayout());

        jPanel1.setBackground(new java.awt.Color(83, 77, 71));
        jPanel1.setMaximumSize(new java.awt.Dimension(481, 436));
        jPanel1.setMinimumSize(new java.awt.Dimension(481, 436));
        jPanel1.setPreferredSize(new java.awt.Dimension(481, 436));
        jPanel1.setLayout(new java.awt.GridBagLayout());

        jLabel1.setBackground(new java.awt.Color(224, 190, 221));
        jLabel1.setFont(new java.awt.Font("Sawasdee", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("<<PERSONALIZADA>>");
        jLabel1.setOpaque(true);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 134;
        gridBagConstraints.ipadx = 304;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(30, 0, 0, 0);
        jPanel1.add(jLabel1, gridBagConstraints);

        Rbtn_Premio.setBackground(new java.awt.Color(137, 132, 126));
        btnGroup_tarjeta1.add(Rbtn_Premio);
        Rbtn_Premio.setForeground(new java.awt.Color(220, 215, 215));
        Rbtn_Premio.setText("Premio");
        Rbtn_Premio.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                Rbtn_PremioItemStateChanged(evt);
            }
        });
        Rbtn_Premio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Rbtn_PremioActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 9;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 8;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(30, 40, 0, 0);
        jPanel1.add(Rbtn_Premio, gridBagConstraints);

        Rbtn_Caminar.setBackground(new java.awt.Color(137, 132, 126));
        btnGroup_tarjeta1.add(Rbtn_Caminar);
        Rbtn_Caminar.setForeground(new java.awt.Color(220, 215, 215));
        Rbtn_Caminar.setText("Caminar");
        Rbtn_Caminar.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                Rbtn_CaminarItemStateChanged(evt);
            }
        });
        Rbtn_Caminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Rbtn_CaminarActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(30, 32, 0, 0);
        jPanel1.add(Rbtn_Caminar, gridBagConstraints);

        Rbtn_moverA.setBackground(new java.awt.Color(137, 132, 126));
        btnGroup_tarjeta1.add(Rbtn_moverA);
        Rbtn_moverA.setForeground(new java.awt.Color(220, 215, 215));
        Rbtn_moverA.setText("Mover a");
        Rbtn_moverA.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                Rbtn_moverAItemStateChanged(evt);
            }
        });
        Rbtn_moverA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Rbtn_moverAActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(12, 32, 0, 0);
        jPanel1.add(Rbtn_moverA, gridBagConstraints);

        Rbtn_vayaCarcel.setBackground(new java.awt.Color(137, 132, 126));
        btnGroup_tarjeta2.add(Rbtn_vayaCarcel);
        Rbtn_vayaCarcel.setForeground(new java.awt.Color(220, 215, 215));
        Rbtn_vayaCarcel.setText("Vaya a cárcel");
        Rbtn_vayaCarcel.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                Rbtn_vayaCarcelItemStateChanged(evt);
            }
        });
        Rbtn_vayaCarcel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Rbtn_vayaCarcelActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 37;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 75;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(12, 29, 0, 0);
        jPanel1.add(Rbtn_vayaCarcel, gridBagConstraints);

        Rbtn_multa.setBackground(new java.awt.Color(137, 132, 126));
        btnGroup_tarjeta2.add(Rbtn_multa);
        Rbtn_multa.setForeground(new java.awt.Color(220, 215, 215));
        Rbtn_multa.setText("Multa");
        Rbtn_multa.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                Rbtn_multaItemStateChanged(evt);
            }
        });
        Rbtn_multa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Rbtn_multaActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 9;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 7;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 40, 0, 0);
        jPanel1.add(Rbtn_multa, gridBagConstraints);

        Rbtn_retroceder.setBackground(new java.awt.Color(137, 132, 126));
        btnGroup_tarjeta1.add(Rbtn_retroceder);
        Rbtn_retroceder.setForeground(new java.awt.Color(220, 215, 215));
        Rbtn_retroceder.setText("Retroceder");
        Rbtn_retroceder.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                Rbtn_retrocederItemStateChanged(evt);
            }
        });
        Rbtn_retroceder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Rbtn_retrocederActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 32, 0, 0);
        jPanel1.add(Rbtn_retroceder, gridBagConstraints);

        Rbtn_pagoATodos.setBackground(new java.awt.Color(137, 132, 126));
        btnGroup_tarjeta2.add(Rbtn_pagoATodos);
        Rbtn_pagoATodos.setForeground(new java.awt.Color(220, 215, 215));
        Rbtn_pagoATodos.setText("Pago a todos");
        Rbtn_pagoATodos.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                Rbtn_pagoATodosItemStateChanged(evt);
            }
        });
        Rbtn_pagoATodos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Rbtn_pagoATodosActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 9;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 21;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(12, 40, 0, 0);
        jPanel1.add(Rbtn_pagoATodos, gridBagConstraints);

        Rbtn_perderTurnos.setBackground(new java.awt.Color(137, 132, 126));
        btnGroup_tarjeta2.add(Rbtn_perderTurnos);
        Rbtn_perderTurnos.setForeground(new java.awt.Color(220, 215, 215));
        Rbtn_perderTurnos.setText("Perder turnos");
        Rbtn_perderTurnos.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                Rbtn_perderTurnosItemStateChanged(evt);
            }
        });
        Rbtn_perderTurnos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Rbtn_perderTurnosActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 37;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 96;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(30, 29, 0, 0);
        jPanel1.add(Rbtn_perderTurnos, gridBagConstraints);

        jLabel2.setForeground(new java.awt.Color(201, 197, 197));
        jLabel2.setText("Descripción:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(32, 36, 0, 0);
        jPanel1.add(jLabel2, gridBagConstraints);

        txt_descripcion.setText(" ");
        txt_descripcion.setEnabled(false);
        txt_descripcion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_descripcionActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.gridwidth = 55;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 287;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(27, 12, 0, 0);
        jPanel1.add(txt_descripcion, gridBagConstraints);

        btn_Aceptar.setFont(new java.awt.Font("Sawasdee", 1, 15)); // NOI18N
        btn_Aceptar.setText("ACEPTAR");
        btn_Aceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_AceptarActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 9;
        gridBagConstraints.gridy = 9;
        gridBagConstraints.gridwidth = 14;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(27, 66, 43, 0);
        jPanel1.add(btn_Aceptar, gridBagConstraints);

        Spn_tarjeta1.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));
        Spn_tarjeta1.setEnabled(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.gridwidth = 6;
        gridBagConstraints.ipadx = 36;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(21, 12, 0, 0);
        jPanel1.add(Spn_tarjeta1, gridBagConstraints);

        lbl_cantidadTarjeta1.setForeground(new java.awt.Color(201, 197, 197));
        lbl_cantidadTarjeta1.setText(" ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.ipadx = 83;
        gridBagConstraints.ipady = 10;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(21, 30, 0, 0);
        jPanel1.add(lbl_cantidadTarjeta1, gridBagConstraints);

        lbl_cantidadTarjeta2.setForeground(new java.awt.Color(201, 197, 197));
        lbl_cantidadTarjeta2.setText(" ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 16;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.gridwidth = 22;
        gridBagConstraints.ipadx = 79;
        gridBagConstraints.ipady = 10;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(21, 1, 0, 0);
        jPanel1.add(lbl_cantidadTarjeta2, gridBagConstraints);

        Spn_tarjeta2.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));
        Spn_tarjeta2.setEnabled(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 57;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.ipadx = 36;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(21, 18, 0, 0);
        jPanel1.add(Spn_tarjeta2, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.gridwidth = 134;
        gridBagConstraints.ipadx = 485;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(14, 0, 0, 0);
        jPanel1.add(jSeparator1, gridBagConstraints);

        Tbtn_aceptar.setFont(new java.awt.Font("Ubuntu", 0, 13)); // NOI18N
        Tbtn_aceptar.setText(">>");
        Tbtn_aceptar.setEnabled(false);
        Tbtn_aceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Tbtn_aceptarActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 57;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 76;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 24;
        gridBagConstraints.ipady = 6;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 68, 0, 0);
        jPanel1.add(Tbtn_aceptar, gridBagConstraints);

        getContentPane().add(jPanel1, new java.awt.GridBagConstraints());

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Rbtn_CaminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Rbtn_CaminarActionPerformed
       
    }//GEN-LAST:event_Rbtn_CaminarActionPerformed

    private void Rbtn_moverAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Rbtn_moverAActionPerformed
        
    }//GEN-LAST:event_Rbtn_moverAActionPerformed

    private void Rbtn_PremioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Rbtn_PremioActionPerformed
      
    }//GEN-LAST:event_Rbtn_PremioActionPerformed

    private void Rbtn_multaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Rbtn_multaActionPerformed
       
    }//GEN-LAST:event_Rbtn_multaActionPerformed

    private void Rbtn_pagoATodosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Rbtn_pagoATodosActionPerformed
     
    }//GEN-LAST:event_Rbtn_pagoATodosActionPerformed

    private void Rbtn_perderTurnosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Rbtn_perderTurnosActionPerformed
       
    }//GEN-LAST:event_Rbtn_perderTurnosActionPerformed

    private void Rbtn_retrocederActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Rbtn_retrocederActionPerformed
        
    }//GEN-LAST:event_Rbtn_retrocederActionPerformed

    private void Rbtn_vayaCarcelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Rbtn_vayaCarcelActionPerformed
      
    }//GEN-LAST:event_Rbtn_vayaCarcelActionPerformed

    private void btn_AceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_AceptarActionPerformed
        this.dispose();
    }//GEN-LAST:event_btn_AceptarActionPerformed

    private void txt_descripcionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_descripcionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_descripcionActionPerformed

    private void Tbtn_aceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Tbtn_aceptarActionPerformed
        Tbtn_aceptar.setEnabled(false);
        deshabilitarBotonesDeTipos();
        habilitarINgreso();
    }//GEN-LAST:event_Tbtn_aceptarActionPerformed

    private void Rbtn_CaminarItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_Rbtn_CaminarItemStateChanged
         tarjetasFusionadas[0]=Rbtn_Caminar.isSelected();              
        establecerCantidadSeleccionados(0);         
        habilitarBotonSIguientes();
    }//GEN-LAST:event_Rbtn_CaminarItemStateChanged

    private void Rbtn_moverAItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_Rbtn_moverAItemStateChanged
         tarjetasFusionadas[1]=Rbtn_moverA.isSelected();
         establecerCantidadSeleccionados(1); 
         habilitarBotonSIguientes();
    }//GEN-LAST:event_Rbtn_moverAItemStateChanged

    private void Rbtn_retrocederItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_Rbtn_retrocederItemStateChanged
         tarjetasFusionadas[2]=Rbtn_retroceder.isSelected();
         establecerCantidadSeleccionados(2);  
         habilitarBotonSIguientes();
    }//GEN-LAST:event_Rbtn_retrocederItemStateChanged

    private void Rbtn_PremioItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_Rbtn_PremioItemStateChanged
          tarjetasFusionadas[3]=Rbtn_Premio.isSelected();
        establecerCantidadSeleccionados(3);    
        habilitarBotonSIguientes();
    }//GEN-LAST:event_Rbtn_PremioItemStateChanged

    private void Rbtn_pagoATodosItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_Rbtn_pagoATodosItemStateChanged
        tarjetasFusionadas[4]=Rbtn_pagoATodos.isSelected();
        establecerCantidadSeleccionados(4); 
        habilitarBotonSIguientes();
    }//GEN-LAST:event_Rbtn_pagoATodosItemStateChanged

    private void Rbtn_multaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_Rbtn_multaItemStateChanged
         tarjetasFusionadas[5]=Rbtn_multa.isSelected();
        establecerCantidadSeleccionados(5);         
        habilitarBotonSIguientes();
    }//GEN-LAST:event_Rbtn_multaItemStateChanged

    private void Rbtn_perderTurnosItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_Rbtn_perderTurnosItemStateChanged
         tarjetasFusionadas[6]=Rbtn_perderTurnos.isSelected();
        establecerCantidadSeleccionados(6);         
        habilitarBotonSIguientes();
    }//GEN-LAST:event_Rbtn_perderTurnosItemStateChanged

    private void Rbtn_vayaCarcelItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_Rbtn_vayaCarcelItemStateChanged
           tarjetasFusionadas[7]=Rbtn_vayaCarcel.isSelected();
         establecerCantidadSeleccionados(7);   
         habilitarBotonSIguientes();
    }//GEN-LAST:event_Rbtn_vayaCarcelItemStateChanged

public boolean habranSeleccionadoIrACarcel(){
    return tarjetasFusionadas[7];
}
    
public boolean[] entregarDesiciones(){
    return  tarjetasFusionadas;
}

public int entregarValorPrimeraTarjeta(){
    return (Integer)Spn_tarjeta1.getValue();
}

public int entregarValorSegundaTarjeta(){
    return (Integer)Spn_tarjeta2.getValue();
}

public String entergarDescripcion(){
    return txt_descripcion.getText();
}

public void establecerCantidadSeleccionados(int tipoSeleccion){//para habiliar el botón
    if(tarjetasFusionadas[tipoSeleccion]){
             cantidadSeleccionados++;
         }else{
             cantidadSeleccionados--;
         }
}

public void habilitarBotonSIguientes(){
    if(cantidadSeleccionados==2){
        Tbtn_aceptar.setEnabled(true);                      
    }   
}

public void habilitarINgreso(){        
        if(tarjetasFusionadas[2]){
            lbl_cantidadTarjeta1.setText("# Casillas");    
            Spn_tarjeta1.setEnabled(true);
            Spn_tarjeta1.setModel(new javax.swing.SpinnerNumberModel(0, 0, numeroCasilla-1, 1));            
        }    
        if(tarjetasFusionadas[3]){
            lbl_cantidadTarjeta1.setText("Premio $:");    
            Spn_tarjeta1.setEnabled(true);
        }
        if(tarjetasFusionadas[4]){
            lbl_cantidadTarjeta2.setText("Pago $:");    
            Spn_tarjeta2.setEnabled(true);            
            txt_descripcion.setEnabled(true);
        }
        if(tarjetasFusionadas[5]){
            lbl_cantidadTarjeta2.setText("Pago $:");    
            Spn_tarjeta2.setEnabled(true);            
            txt_descripcion.setEnabled(true);            
        }
        if(tarjetasFusionadas[6]){
            lbl_cantidadTarjeta2.setText("# Turnos:");    
            Spn_tarjeta2.setEnabled(true);            
            txt_descripcion.setEnabled(true);
        }        
        if(tarjetasFusionadas[7]){            
            lbl_cantidadTarjeta2.setText("# Turnos:");    
            Spn_tarjeta2.setEnabled(true);            
//            Spn_tarjeta2.setModel(new javax.swing.SpinnerNumberModel(0, 2, null, 1));//pues la casilla manda por un turno, así que aquí sea de 2 en ad, sino que chiste xD
            txt_descripcion.setEnabled(true);
        }
        
        txt_descripcion.updateUI();
    }

    public void deshabilitarBotonesDeTipos(){
        Rbtn_Caminar.setEnabled(false);
        Rbtn_Premio.setEnabled(false);
        Rbtn_moverA.setEnabled(false);
        Rbtn_multa.setEnabled(false);
        Rbtn_pagoATodos.setEnabled(false);
        Rbtn_perderTurnos.setEnabled(false);
        Rbtn_retroceder.setEnabled(false);        
        Rbtn_vayaCarcel.setEnabled(false);        
    }

    public void establecerPermisoParaIrACarcel(boolean permiso){
           permisoParaIrCarcel=permiso;//De esta manera s asigna el valor correspondiente, si necesidad de estar revisando el valor como se hizo para el caso detTjt           
           Rbtn_vayaCarcel.setEnabled(permiso);
    }//En la primera línea se evita tener que crear un método a parte para saber cuando habi y deshabi el btn cada vez que se establezca el valor de permisión
    
public void recibirCasilaFisica(JPanel casilla){
    JLabel labelIndice=(JLabel)casilla.getComponent(1);//será utl para retroceso ya que deberá darsele una cdad a partir de su ubicacion, es decir quel el índice-1 será la cdad de casillas que podrá recorrer sin llegar al inicio
    numeroCasilla=Integer.parseInt(labelIndice.getText());
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton Rbtn_Caminar;
    private javax.swing.JRadioButton Rbtn_Premio;
    private javax.swing.JRadioButton Rbtn_moverA;
    private javax.swing.JRadioButton Rbtn_multa;
    private javax.swing.JRadioButton Rbtn_pagoATodos;
    private javax.swing.JRadioButton Rbtn_perderTurnos;
    private javax.swing.JRadioButton Rbtn_retroceder;
    private javax.swing.JRadioButton Rbtn_vayaCarcel;
    private javax.swing.JSpinner Spn_tarjeta1;
    private javax.swing.JSpinner Spn_tarjeta2;
    private javax.swing.JToggleButton Tbtn_aceptar;
    private javax.swing.ButtonGroup btnGroup_tarjeta1;
    private javax.swing.ButtonGroup btnGroup_tarjeta2;
    private javax.swing.JButton btn_Aceptar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lbl_cantidadTarjeta1;
    private javax.swing.JLabel lbl_cantidadTarjeta2;
    private javax.swing.JTextField txt_descripcion;
    // End of variables declaration//GEN-END:variables
}

