/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package FrontendBancopoly;

import BackendBancopoly.Nodo;
import Casillas.Casilla;
import Casillas.Estacion;
import Casillas.Servicio;
import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author phily
 */
public class CustomizacionServicioYEstacion extends javax.swing.JDialog {
     JPanel casillaResidencia;
        Casilla casilla;//será útil para el envío de la casilla al método de customización principal
        Casilla casillaCreada;
        String tipoPropiedad;
    
        
    /**
     * Creates new form CustomizacionServicioYEstacion
     */
    public CustomizacionServicioYEstacion(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }
    
     public void recibirCasillaResidencia(JPanel casillFisica, String tipoDePropiedad){
        casillaResidencia=casillFisica;
        tipoPropiedad=tipoDePropiedad;
        
  
                if(tipoDePropiedad.equalsIgnoreCase("servicio básico")){
                    lbl_titulo.setText("SERVICIO BÁSICO");
                }else{
                    lbl_titulo.setText("ESTACIÓN");//pues como está aquí solo podía ser esa xD
                }        
        }               
  

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lbl_titulo = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        TxtF_nombreElemento = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        lbl_pagoUso = new javax.swing.JLabel();
        Spn_pagoCosto = new javax.swing.JSpinner();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        Spn_pagoCompra = new javax.swing.JSpinner();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(511, 483));
        setMinimumSize(new java.awt.Dimension(511, 483));
        setPreferredSize(new java.awt.Dimension(511, 483));

        jPanel1.setBackground(new java.awt.Color(83, 77, 71));

        lbl_titulo.setBackground(new java.awt.Color(242, 145, 111));
        lbl_titulo.setFont(new java.awt.Font("Sawasdee", 1, 18)); // NOI18N
        lbl_titulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_titulo.setText(" ");
        lbl_titulo.setOpaque(true);

        jLabel2.setFont(new java.awt.Font("Sawasdee", 1, 15)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(227, 220, 220));
        jLabel2.setText("Nombre elemento:");

        TxtF_nombreElemento.setText(" ");
        TxtF_nombreElemento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtF_nombreElementoActionPerformed(evt);
            }
        });
        TxtF_nombreElemento.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                TxtF_nombreElementoKeyPressed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Sawasdee", 0, 15)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(217, 205, 205));
        jLabel3.setText("-> Pagos");

        lbl_pagoUso.setFont(new java.awt.Font("Sawasdee", 0, 15)); // NOI18N
        lbl_pagoUso.setForeground(new java.awt.Color(211, 204, 204));
        lbl_pagoUso.setText("Por uso:");

        Spn_pagoCosto.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));

        jButton1.setText("ACEPTAR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Sawasdee", 0, 15)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(230, 221, 221));
        jLabel1.setText("Por compra:");

        Spn_pagoCompra.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbl_titulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(72, 72, 72)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(39, 39, 39)
                        .addComponent(TxtF_nombreElemento, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(102, 102, 102)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_pagoUso, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(43, 43, 43)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Spn_pagoCompra)
                            .addComponent(Spn_pagoCosto, javax.swing.GroupLayout.DEFAULT_SIZE, 69, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addComponent(jLabel3)))
                .addContainerGap(77, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(53, 53, 53))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(lbl_titulo, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(106, 106, 106)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(TxtF_nombreElemento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_pagoUso)
                    .addComponent(Spn_pagoCosto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Spn_pagoCompra, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 107, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(27, 27, 27))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TxtF_nombreElementoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtF_nombreElementoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtF_nombreElementoActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        switch(tipoPropiedad){            
            case "Servicio básico":
                this.dispose();
                Casilla casillaServicio = new Servicio(casillaResidencia, SolicitudDatos.registroDatos.obtnerInteres(), TxtF_nombreElemento.getText().trim(), 
                       (Integer)Spn_pagoCosto.getValue(), (Integer)Spn_pagoCompra.getValue());
                casillaCreada= casillaServicio;
            break;    
                
            case "Estación":            
                this.dispose();
                Casilla casillaEstacion = new Estacion(casillaResidencia, SolicitudDatos.registroDatos.obtnerInteres(), TxtF_nombreElemento.getText().trim(), 
                       (Integer)Spn_pagoCosto.getValue(), (Integer)Spn_pagoCompra.getValue());
                casillaCreada= casillaEstacion;
            break;    
                
        }               
        SolicitudDatos.registroDatos.incrementarNumeroPropiedadesTotales();//de esta manera de ahí en add, solo restarác comparar con este valor para determinar de una manera al ganado
    }//GEN-LAST:event_jButton1ActionPerformed

    private void TxtF_nombreElementoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtF_nombreElementoKeyPressed
    String ingresado=TxtF_nombreElemento.getText().trim();        
        
       if(evt.getKeyCode()==KeyEvent.VK_ENTER){
           switch(tipoPropiedad){
               
               case "Servicio básico":
                   if(!SolicitudDatos.registroDatos.obtenerListaElementosServicios().estaVacia()){
                       Nodo<String> auxilair;
                       auxilair = SolicitudDatos.registroDatos.obtenerListaElementosServicios().obtnerPrimerNodo();                   
                        while(auxilair!=null && !auxilair.obtenerObjectcEnCasilla().equalsIgnoreCase(ingresado)){
                            auxilair.obtenerSiguiente();
                        }//fin del while
                    
                        if(auxilair.obtenerObjectcEnCasilla().equalsIgnoreCase(ingresado)){
                            TxtF_nombreElemento.setText("");
                        JOptionPane.showMessageDialog(this, "Ya has ingresado un servicio con ese nombre", "Existente", JOptionPane.INFORMATION_MESSAGE);
                        }else{
                            guardarListadosSegunTIpo(ingresado);                
                        }
                    
                  }
               
               break;
               
               case "Estación":
                   if(!SolicitudDatos.registroDatos.obtenerListaElementosEstaciones().estaVacia()){
                       Nodo<String> auxilair;
                       auxilair = SolicitudDatos.registroDatos.obtenerListaElementosEstaciones().obtnerPrimerNodo();                   
                        while(auxilair!=null && !auxilair.obtenerObjectcEnCasilla().equalsIgnoreCase(ingresado)){
                            auxilair.obtenerSiguiente();
                        }//fin del while
                    
                        if(auxilair.obtenerObjectcEnCasilla().equalsIgnoreCase(ingresado)){
                            TxtF_nombreElemento.setText("");
                        JOptionPane.showMessageDialog(this, "Ya has ingresado un servicio con ese nombre", "Existente", JOptionPane.INFORMATION_MESSAGE);
                        }else{
                            guardarListadosSegunTIpo(ingresado);                
                        }
                    
                  } 
            
                break;           
           }//fin del switch
           
       }       
    }//GEN-LAST:event_TxtF_nombreElementoKeyPressed

     public void guardarListadosSegunTIpo(String nuevoGrupo){
        switch(tipoPropiedad){            
            case "Servicio básico":
                SolicitudDatos.registroDatos.agregarGruposDeServicios(nuevoGrupo);//esto se va a volver en los nombres de los servicios puesto que no tiene grupos, de tal manera que no se puedan repetir, pero para nada más que eso sirve este listado
                //de forma similar par ael de estación
            break;
            
            case "Estación":
                SolicitudDatos.registroDatos.agregarGruposDeEstaciones(nuevoGrupo);
            break;
        }
    }
     
     public Casilla retornarCasillaLógica(){       
            return casillaCreada;//De esta forma no tengo que estar escogiendo entre que método enviar según la casilla creada 
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSpinner Spn_pagoCompra;
    private javax.swing.JSpinner Spn_pagoCosto;
    private javax.swing.JTextField TxtF_nombreElemento;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbl_pagoUso;
    private javax.swing.JLabel lbl_titulo;
    // End of variables declaration//GEN-END:variables
}
