/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package FrontendBancopoly;

import Casillas.Casilla;
import Casillas.TomaUnaTarjeta;
import javax.swing.*;

/**
 *
 * @author phily
 */
public class CustomizacionTomaTarjeta extends javax.swing.JDialog {
        JPanel casillaResidencial;     
        private boolean tarjetaEscogidas[]= new boolean[10];
        private boolean permisoHabilitarVayaCarcel=true;//será cambiado cuando se guarde el objt toma una tjt en la custom principal y hasta que tenga a su cárcel xD
        Casilla casilla;

    /**
     * Creates new form CustomizacionTomaTarjeta
     */
    public CustomizacionTomaTarjeta(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
      
        
        //también tienes que reestablecer el valor de la variable de selección de la opción VC
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JPn_tomarTarjeta = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        txtF_breveDescripcion = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        cBx_tipoTarjeta = new javax.swing.JComboBox<>();
        chkBx_caminar = new javax.swing.JCheckBox();
        chkBx_retroceder = new javax.swing.JCheckBox();
        chkBx_Multa = new javax.swing.JCheckBox();
        ckBx_Premio = new javax.swing.JCheckBox();
        chkBx_moverA = new javax.swing.JCheckBox();
        chkBx_PagarA = new javax.swing.JCheckBox();
        chkBx_PerderTurno = new javax.swing.JCheckBox();
        chkBx_irCarcel = new javax.swing.JCheckBox();
        chkBx_Personalizada = new javax.swing.JCheckBox();
        jLabel15 = new javax.swing.JLabel();
        chkBx_SalirCarcel = new javax.swing.JCheckBox();
        Spn_numeroRepeticiones = new javax.swing.JSpinner();
        btn_aceptarTarjeta = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(511, 483));
        setMinimumSize(new java.awt.Dimension(511, 483));
        setResizable(false);

        JPn_tomarTarjeta.setBackground(new java.awt.Color(83, 77, 71));
        JPn_tomarTarjeta.setMaximumSize(new java.awt.Dimension(511, 483));
        JPn_tomarTarjeta.setMinimumSize(new java.awt.Dimension(511, 483));

        jLabel12.setBackground(new java.awt.Color(243, 223, 165));
        jLabel12.setFont(new java.awt.Font("Sawasdee", 1, 18)); // NOI18N
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("<<TOMAR TARJETA>>");
        jLabel12.setOpaque(true);

        jLabel13.setForeground(new java.awt.Color(217, 210, 210));
        jLabel13.setText("Breve descripción :");

        txtF_breveDescripcion.setText(" ");

        jLabel14.setForeground(new java.awt.Color(206, 196, 196));
        jLabel14.setText("Tipo de tarjetas a mostrar :");

        cBx_tipoTarjeta.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Beneficiosa", "Maliciosa", "Variada" }));
        cBx_tipoTarjeta.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cBx_tipoTarjetaItemStateChanged(evt);
            }
        });

        chkBx_caminar.setBackground(new java.awt.Color(83, 77, 71));
        chkBx_caminar.setForeground(new java.awt.Color(221, 210, 210));
        chkBx_caminar.setText("Caminar");
        chkBx_caminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkBx_caminarActionPerformed(evt);
            }
        });

        chkBx_retroceder.setBackground(new java.awt.Color(83, 77, 71));
        chkBx_retroceder.setForeground(new java.awt.Color(221, 210, 210));
        chkBx_retroceder.setText("Retroceder");
        chkBx_retroceder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkBx_retrocederActionPerformed(evt);
            }
        });

        chkBx_Multa.setBackground(new java.awt.Color(83, 77, 71));
        chkBx_Multa.setForeground(new java.awt.Color(221, 210, 210));
        chkBx_Multa.setText("Multa");
        chkBx_Multa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkBx_MultaActionPerformed(evt);
            }
        });

        ckBx_Premio.setBackground(new java.awt.Color(83, 77, 71));
        ckBx_Premio.setForeground(new java.awt.Color(221, 210, 210));
        ckBx_Premio.setText("Premio");
        ckBx_Premio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ckBx_PremioActionPerformed(evt);
            }
        });

        chkBx_moverA.setBackground(new java.awt.Color(83, 77, 71));
        chkBx_moverA.setForeground(new java.awt.Color(221, 210, 210));
        chkBx_moverA.setText("Mover a casilla");
        chkBx_moverA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkBx_moverAActionPerformed(evt);
            }
        });

        chkBx_PagarA.setBackground(new java.awt.Color(83, 77, 71));
        chkBx_PagarA.setForeground(new java.awt.Color(221, 210, 210));
        chkBx_PagarA.setText("Pagar a los demás");
        chkBx_PagarA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkBx_PagarAActionPerformed(evt);
            }
        });

        chkBx_PerderTurno.setBackground(new java.awt.Color(83, 77, 71));
        chkBx_PerderTurno.setForeground(new java.awt.Color(221, 210, 210));
        chkBx_PerderTurno.setText("Perder turno[s]");
        chkBx_PerderTurno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkBx_PerderTurnoActionPerformed(evt);
            }
        });

        chkBx_irCarcel.setBackground(new java.awt.Color(83, 77, 71));
        chkBx_irCarcel.setForeground(new java.awt.Color(221, 210, 210));
        chkBx_irCarcel.setText("Ir a la cárcel");
        chkBx_irCarcel.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                chkBx_irCarcelItemStateChanged(evt);
            }
        });
        chkBx_irCarcel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkBx_irCarcelActionPerformed(evt);
            }
        });

        chkBx_Personalizada.setBackground(new java.awt.Color(83, 77, 71));
        chkBx_Personalizada.setForeground(new java.awt.Color(221, 210, 210));
        chkBx_Personalizada.setText("Personalizada");
        chkBx_Personalizada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkBx_PersonalizadaActionPerformed(evt);
            }
        });

        jLabel15.setForeground(new java.awt.Color(221, 210, 210));
        jLabel15.setText("Cantidad por cada una :");

        chkBx_SalirCarcel.setBackground(new java.awt.Color(83, 77, 71));
        chkBx_SalirCarcel.setForeground(new java.awt.Color(221, 210, 210));
        chkBx_SalirCarcel.setText("Salga de la cárcel");
        chkBx_SalirCarcel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkBx_SalirCarcelActionPerformed(evt);
            }
        });

        Spn_numeroRepeticiones.setModel(new javax.swing.SpinnerNumberModel(1, 1, 10, 1));

        btn_aceptarTarjeta.setText("ACEPTAR");
        btn_aceptarTarjeta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_aceptarTarjetaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout JPn_tomarTarjetaLayout = new javax.swing.GroupLayout(JPn_tomarTarjeta);
        JPn_tomarTarjeta.setLayout(JPn_tomarTarjetaLayout);
        JPn_tomarTarjetaLayout.setHorizontalGroup(
            JPn_tomarTarjetaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(JPn_tomarTarjetaLayout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addGroup(JPn_tomarTarjetaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(JPn_tomarTarjetaLayout.createSequentialGroup()
                        .addGroup(JPn_tomarTarjetaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(JPn_tomarTarjetaLayout.createSequentialGroup()
                                .addGap(40, 40, 40)
                                .addGroup(JPn_tomarTarjetaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(JPn_tomarTarjetaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(JPn_tomarTarjetaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(chkBx_Multa)
                                            .addComponent(chkBx_irCarcel))
                                        .addComponent(chkBx_caminar, javax.swing.GroupLayout.Alignment.LEADING))
                                    .addComponent(chkBx_SalirCarcel)
                                    .addComponent(chkBx_retroceder)))
                            .addComponent(jLabel15))
                        .addGap(36, 36, 36)
                        .addGroup(JPn_tomarTarjetaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(JPn_tomarTarjetaLayout.createSequentialGroup()
                                .addGap(0, 125, Short.MAX_VALUE)
                                .addComponent(btn_aceptarTarjeta))
                            .addComponent(chkBx_PerderTurno)
                            .addComponent(ckBx_Premio)
                            .addComponent(chkBx_moverA)
                            .addComponent(chkBx_PagarA)
                            .addComponent(chkBx_Personalizada)))
                    .addGroup(JPn_tomarTarjetaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(JPn_tomarTarjetaLayout.createSequentialGroup()
                            .addComponent(jLabel13)
                            .addGap(31, 31, 31)
                            .addComponent(txtF_breveDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JPn_tomarTarjetaLayout.createSequentialGroup()
                            .addComponent(jLabel14)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(JPn_tomarTarjetaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(Spn_numeroRepeticiones, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(cBx_tipoTarjeta, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(22, 22, 22))
        );
        JPn_tomarTarjetaLayout.setVerticalGroup(
            JPn_tomarTarjetaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPn_tomarTarjetaLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(jLabel12)
                .addGap(23, 23, 23)
                .addGroup(JPn_tomarTarjetaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(txtF_breveDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(JPn_tomarTarjetaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(cBx_tipoTarjeta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(JPn_tomarTarjetaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chkBx_caminar)
                    .addComponent(ckBx_Premio))
                .addGap(18, 18, 18)
                .addGroup(JPn_tomarTarjetaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chkBx_SalirCarcel)
                    .addComponent(chkBx_moverA))
                .addGap(28, 28, 28)
                .addGroup(JPn_tomarTarjetaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chkBx_retroceder)
                    .addComponent(chkBx_PagarA))
                .addGap(18, 18, 18)
                .addGroup(JPn_tomarTarjetaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chkBx_Multa)
                    .addComponent(chkBx_PerderTurno))
                .addGap(18, 18, 18)
                .addGroup(JPn_tomarTarjetaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chkBx_irCarcel)
                    .addComponent(chkBx_Personalizada))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addGroup(JPn_tomarTarjetaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(Spn_numeroRepeticiones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_aceptarTarjeta))
                .addGap(16, 16, 16))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(JPn_tomarTarjeta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(JPn_tomarTarjeta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void chkBx_moverAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkBx_moverAActionPerformed
        tarjetaEscogidas[3]= chkBx_moverA.isSelected();        
    }//GEN-LAST:event_chkBx_moverAActionPerformed

    private void btn_aceptarTarjetaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_aceptarTarjetaActionPerformed
        this.dispose();
        //tal vez suceda por el hecho de que no se crea como una casilla
        TomaUnaTarjeta casillaTomaTarjeta = new TomaUnaTarjeta(casillaResidencial, tarjetaEscogidas,(Integer) Spn_numeroRepeticiones.getValue());//recibirá los valores de verdad de cada chBx, dependiendo de su selección o no     
        casilla=casillaTomaTarjeta;
    }//GEN-LAST:event_btn_aceptarTarjetaActionPerformed

    private void chkBx_irCarcelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkBx_irCarcelActionPerformed
        
    }//GEN-LAST:event_chkBx_irCarcelActionPerformed

    private void chkBx_irCarcelItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_chkBx_irCarcelItemStateChanged
         tarjetaEscogidas[8] = (chkBx_irCarcel.isSelected())? true:false;
         //lo estoy haciendo así solo para que cuando deba enviar datos individuales se vea más rápido que tipo de dato se está enviando...auqnue eso lo dice el nombre del método xD
    }//GEN-LAST:event_chkBx_irCarcelItemStateChanged

    private void chkBx_caminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkBx_caminarActionPerformed
        tarjetaEscogidas[0] = chkBx_caminar.isSelected();
        
    }//GEN-LAST:event_chkBx_caminarActionPerformed

    private void ckBx_PremioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ckBx_PremioActionPerformed
        tarjetaEscogidas[1]= ckBx_Premio.isSelected();        
    }//GEN-LAST:event_ckBx_PremioActionPerformed

    private void chkBx_SalirCarcelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkBx_SalirCarcelActionPerformed
        tarjetaEscogidas[2]=chkBx_SalirCarcel.isSelected();        
    }//GEN-LAST:event_chkBx_SalirCarcelActionPerformed

    private void chkBx_retrocederActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkBx_retrocederActionPerformed
        tarjetaEscogidas[4]=chkBx_retroceder.isSelected();        
    }//GEN-LAST:event_chkBx_retrocederActionPerformed

    private void chkBx_PagarAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkBx_PagarAActionPerformed
        tarjetaEscogidas[5]=chkBx_PagarA.isSelected();        
    }//GEN-LAST:event_chkBx_PagarAActionPerformed

    private void chkBx_MultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkBx_MultaActionPerformed
        tarjetaEscogidas[6]= chkBx_Multa.isSelected();        
    }//GEN-LAST:event_chkBx_MultaActionPerformed

    private void chkBx_PerderTurnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkBx_PerderTurnoActionPerformed
        tarjetaEscogidas[7]=chkBx_PerderTurno.isSelected();        
    }//GEN-LAST:event_chkBx_PerderTurnoActionPerformed

    private void chkBx_PersonalizadaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkBx_PersonalizadaActionPerformed
        tarjetaEscogidas[9]=chkBx_Personalizada.isSelected();        
    }//GEN-LAST:event_chkBx_PersonalizadaActionPerformed

    private void cBx_tipoTarjetaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cBx_tipoTarjetaItemStateChanged
        switch(cBx_tipoTarjeta.getSelectedIndex()){
            case 0://beneficiosas
                chkBx_Multa.setEnabled(false);
                chkBx_PagarA.setEnabled(false);
                chkBx_PerderTurno.setEnabled(false);
                chkBx_Personalizada.setEnabled(false);
                chkBx_SalirCarcel.setEnabled(true);
                chkBx_caminar.setEnabled(true);
                ckBx_Premio.setEnabled(true);
                chkBx_irCarcel.setEnabled(false);
                chkBx_retroceder.setEnabled(false);                
                chkBx_moverA.setEnabled(true);                
            break;
            
            case 1://maliciosas
                chkBx_Multa.setEnabled(true);
                chkBx_PagarA.setEnabled(true);
                chkBx_PerderTurno.setEnabled(true);
                chkBx_Personalizada.setEnabled(false);
                chkBx_SalirCarcel.setEnabled(false);
                chkBx_caminar.setEnabled(false);
                ckBx_Premio.setEnabled(false);
                if(permisoHabilitarVayaCarcel){
                    chkBx_irCarcel.setEnabled(true);
                }                
                chkBx_retroceder.setEnabled(true);                
                chkBx_moverA.setEnabled(true);
            break;
            
            case 2://variadas
                chkBx_Multa.setEnabled(true);
                chkBx_PagarA.setEnabled(true);
                chkBx_PerderTurno.setEnabled(true);
                chkBx_Personalizada.setEnabled(true);
                chkBx_SalirCarcel.setEnabled(true);
                chkBx_caminar.setEnabled(true);
                ckBx_Premio.setEnabled(true);
                if(permisoHabilitarVayaCarcel){
                    chkBx_irCarcel.setEnabled(true);
                }                
                chkBx_retroceder.setEnabled(true);                
                chkBx_moverA.setEnabled(true);
            break;
        }
    }//GEN-LAST:event_cBx_tipoTarjetaItemStateChanged

    public void deseleccionarTodasxD(){
              chkBx_Multa.setSelected(false);
                chkBx_PagarA.setSelected(false);
                chkBx_PerderTurno.setSelected(false);
                chkBx_Personalizada.setSelected(false);
                chkBx_SalirCarcel.setSelected(false);
                chkBx_caminar.setSelected(false);
                ckBx_Premio.setSelected(false);           
                chkBx_irCarcel.setSelected(false);              
                chkBx_retroceder.setSelected(false);                
                chkBx_moverA.setSelected(false);
                
                reestablecerValorVariables();
    }
    
    public void reestablecerValorVariables(){
        for (int tipoTarjeta = 0; tipoTarjeta < tarjetaEscogidas.length; tipoTarjeta++) {
            tarjetaEscogidas[tipoTarjeta]=false;
        }
    }
    
    /**
     *método empleado para informarle a la customización principal que debe almacenar la casilla enviada a su 
     * respectiva variable, para luego mandarle la cárcel que espera
     * @return
     */
    public boolean hanSeleccionadoVayaCarcel(){
        return tarjetaEscogidas[8];
    }
    
    public boolean hanSeleccionadoCasillaQueMUeve(){//OJO estos valores también se hacen true al recibirlos de la casilla, esto cuando en personalizda hayan seleccionado cualquiera de estos 2 <- mejor se reciben directamente de personalizada, pues ella sabe realmente como está la cosa
        TomaUnaTarjeta auxiliar;
        auxiliar= (TomaUnaTarjeta)casilla;
        return tarjetaEscogidas[0] || tarjetaEscogidas[3] || auxiliar.hanSeleccionadoEnPersonalizadaCasillaQueMueve();//asumo que lo que hará es si cualquiera de ellas es V, entonces dará V sino F.... si da problema será porque no devuelve los datos según lo había imaginado
    }
    
    public void reestablecerPermisoHabilitacionVayaCarcel(boolean sePermite){
        tarjetaEscogidas[8]=false;//este después de cada vez que haya sido seleccionado, debe volver a flase porque sino a la próxima que pregunte la costum principal si lo hicieron, dirá que si aunque no haya sido así
        permisoHabilitarVayaCarcel=sePermite;
        establecerEstadoVayaCarcel();
    }
    
    public void establecerEstadoVayaCarcel(){
          if(!permisoHabilitarVayaCarcel){
            //chkBx_irCarcel.setSelected(false);//tb podrías hacerlo con todos los demás 
            chkBx_irCarcel.setEnabled(false);
        }else{                
                chkBx_irCarcel.setEnabled(true);
        }
          
          chkBx_irCarcel.updateUI();
    }
    
    public Casilla retornarCasillaLogica(){
        return casilla;//al parecer está entrando 2 veces al método y para la 2da vez ya no devuelve nada...pero,inspecciona bien, porque las casillas tienen su valor
    }
    
    public void recibirCasillaFisica(JPanel casillaEnCuestion){
        casillaResidencial = casillaEnCuestion;
    }    
       

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel JPn_tomarTarjeta;
    private javax.swing.JSpinner Spn_numeroRepeticiones;
    private javax.swing.JButton btn_aceptarTarjeta;
    private javax.swing.JComboBox<String> cBx_tipoTarjeta;
    private javax.swing.JCheckBox chkBx_Multa;
    private javax.swing.JCheckBox chkBx_PagarA;
    private javax.swing.JCheckBox chkBx_PerderTurno;
    private javax.swing.JCheckBox chkBx_Personalizada;
    private javax.swing.JCheckBox chkBx_SalirCarcel;
    private javax.swing.JCheckBox chkBx_caminar;
    private javax.swing.JCheckBox chkBx_irCarcel;
    private javax.swing.JCheckBox chkBx_moverA;
    private javax.swing.JCheckBox chkBx_retroceder;
    private javax.swing.JCheckBox ckBx_Premio;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JTextField txtF_breveDescripcion;
    // End of variables declaration//GEN-END:variables
}
