/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package FrontendBancopoly;

/**
 *
 * @author phily
 */
public class Facturita extends javax.swing.JDialog {
    boolean esAdquisicion;
    
    /**
     * Creates new form Facturita
     */
    public Facturita(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lbl_cdadSimple = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lbl_subtotalSImple = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        lbl_cdadSofisticada = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        lbl_total = new javax.swing.JLabel();
        lbl_precioUdSimples = new javax.swing.JLabel();
        lbl_precioUdSofisticada = new javax.swing.JLabel();
        lbl_subtotalSofisticada = new javax.swing.JLabel();
        btn_aceptar = new javax.swing.JButton();
        btn_declinar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(244, 241, 239));

        jLabel1.setBackground(new java.awt.Color(255, 254, 254));
        jLabel1.setFont(new java.awt.Font("Sawasdee", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("<<FACTURA>>");
        jLabel1.setOpaque(true);

        jLabel2.setBackground(new java.awt.Color(249, 232, 215));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Cantidad");
        jLabel2.setOpaque(true);

        jLabel3.setBackground(new java.awt.Color(249, 232, 215));
        jLabel3.setText("Por:");
        jLabel3.setOpaque(true);

        lbl_cdadSimple.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        lbl_cdadSimple.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_cdadSimple.setText(" ");

        jLabel4.setFont(new java.awt.Font("Sawasdee", 0, 15)); // NOI18N
        jLabel4.setText("cosntrucción simple");

        lbl_subtotalSImple.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        lbl_subtotalSImple.setText(" ");

        jLabel7.setFont(new java.awt.Font("Sawasdee", 0, 14)); // NOI18N
        jLabel7.setText("Precio unitario $:");

        lbl_cdadSofisticada.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        lbl_cdadSofisticada.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_cdadSofisticada.setText(" ");

        jLabel9.setFont(new java.awt.Font("Sawasdee", 0, 15)); // NOI18N
        jLabel9.setText("construccion sofisticada");

        jLabel10.setFont(new java.awt.Font("Sawasdee", 0, 14)); // NOI18N
        jLabel10.setText("Precio unitario $:");

        jLabel11.setText(" ");

        jLabel12.setFont(new java.awt.Font("Sawasdee", 1, 17)); // NOI18N
        jLabel12.setText("Total $:");

        lbl_total.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        lbl_total.setText(" ");

        lbl_precioUdSimples.setFont(new java.awt.Font("Ubuntu", 0, 14)); // NOI18N
        lbl_precioUdSimples.setText("jLabel14");

        lbl_precioUdSofisticada.setFont(new java.awt.Font("Ubuntu", 0, 14)); // NOI18N
        lbl_precioUdSofisticada.setText("jLabel15");

        lbl_subtotalSofisticada.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        lbl_subtotalSofisticada.setText("jLabel16");

        btn_aceptar.setBackground(new java.awt.Color(237, 214, 195));
        btn_aceptar.setText("ACEPTAR");
        btn_aceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_aceptarActionPerformed(evt);
            }
        });

        btn_declinar.setText("DECLINAR");
        btn_declinar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_declinarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbl_precioUdSofisticada)
                        .addGap(35, 35, 35)
                        .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, 7, Short.MAX_VALUE)
                        .addGap(74, 74, 74))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel7)
                        .addGap(18, 18, 18)
                        .addComponent(lbl_precioUdSimples)
                        .addGap(115, 115, 115))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lbl_cdadSofisticada, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(31, 31, 31)
                                .addComponent(jLabel9))
                            .addComponent(lbl_cdadSimple, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(lbl_subtotalSImple, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addContainerGap())
                            .addComponent(lbl_subtotalSofisticada, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addGap(37, 37, 37)
                        .addComponent(lbl_total, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(13, 13, 13))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(btn_aceptar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btn_declinar)
                        .addGap(104, 104, 104))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_cdadSimple, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_subtotalSImple, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(lbl_precioUdSimples))
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_subtotalSofisticada, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(lbl_cdadSofisticada, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl_precioUdSofisticada)
                            .addComponent(jLabel10))))
                .addGap(35, 35, 35)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(lbl_total, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_aceptar)
                    .addComponent(btn_declinar))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_aceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_aceptarActionPerformed
        esAdquisicion=true;
        this.dispose();
    }//GEN-LAST:event_btn_aceptarActionPerformed

    private void btn_declinarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_declinarActionPerformed
        this.dispose();
    }//GEN-LAST:event_btn_declinarActionPerformed

    public void limpiarParaNuevosDatos(){
        lbl_cdadSimple.setText("");
        lbl_cdadSofisticada.setText("");
        lbl_precioUdSimples.setText("");
        lbl_precioUdSofisticada.setText("");
        lbl_subtotalSImple.setText("");
        lbl_subtotalSofisticada.setText("");
        lbl_total.setText("");
    }
    

    public void establecerDatosFactura(int cantidadSImples, int cantidadSofisticadas, int PrecioSImples, int precioSofisticadas, int total){
        esAdquisicion=false;//De una vez xD
        
        lbl_cdadSimple.setText(String.valueOf(cantidadSImples));
        lbl_cdadSofisticada.setText(String.valueOf(cantidadSofisticadas));
        lbl_precioUdSimples.setText(String.valueOf(PrecioSImples));
        lbl_precioUdSofisticada.setText(String.valueOf(precioSofisticadas));
        lbl_subtotalSImple.setText(String.valueOf(cantidadSImples*PrecioSImples));
        lbl_subtotalSofisticada.setText(String.valueOf(cantidadSofisticadas*precioSofisticadas));
        lbl_total.setText(String.valueOf(total));
    }
    
    public boolean retornarDecision(){
        return esAdquisicion;
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_aceptar;
    private javax.swing.JButton btn_declinar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbl_cdadSimple;
    private javax.swing.JLabel lbl_cdadSofisticada;
    private javax.swing.JLabel lbl_precioUdSimples;
    private javax.swing.JLabel lbl_precioUdSofisticada;
    private javax.swing.JLabel lbl_subtotalSImple;
    private javax.swing.JLabel lbl_subtotalSofisticada;
    private javax.swing.JLabel lbl_total;
    // End of variables declaration//GEN-END:variables
}
