/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package FrontendBancopoly;

/**
 *
 * @author phily
 */
public class MisPoseciones extends javax.swing.JFrame {

    /**
     * Creates new form MisPoseciones
     */
    public MisPoseciones() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane4 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jTextArea1.setText("La opción de hipotecar se habilitará \nen el momento que se quede sin \npropiedades en dicho lugar, lo cual se\nrepresentará al desactivar la opción \nde vender y con ello activar la de\n hipotecar\n\nRECUERDA, en los listados solamente\naparecerán las propiedades que a él \nle correspondan, lo cual se hará acce\ndiendo al listado del objeto propieda\ndes del jugador con esto quiero decir \nque al comprar lo que se le pasará será solamente\nel objetopropiedad del grupo corresp\nNO la renta al valor de ella se accede\nrá directamente desde el método res\npectivo para \"obtener\" el pago, lo\ncual se encuentra en la hija respectiv\na de la clase de \"casillas\", es decir que\nNO SE LE PASARÁN VALORES, SINO\nLOS OBJETOS EN SÍ, para acceder a\nsus respectivos miembros\n\npor ello al comprar casas se irá direct\nal arr de edificaciones simples de la \nhija del grupo de la propiedad respec\ntiva\n\nLos grupos de las propiedades que se\ntomarán en cta para formar las hijas\nsolo son los establecidos por las\nespecificaciones del juego, no los\ngrupos que se creen por el jugador\nestos serán solo una nueva refer\nal grupo general donde en una var\nse le indicará el nombre que el jug\nle halla asignado,( mira tu cuaderno)\nel tamaño del arreglo se definirá \nsegún el # de grupos totales de cada \npropiedad que halla creado el jug\nes decir que se hará hasta el final de\nla customización del mapa, lo que si\nya estará creado al crear el mapa\nserá el arreglo que contiene todas\nlas casillas que son útiles para la crea\nción y edición de dicho mapa, cuando \npresione jugar se creará el arreglo \nde propiedad correspondiente, \nsegún lo especificado, esto podrá\nhacerse al acceder al tamaño de la \nlista y a los elementos de ella.");
        jScrollPane4.setViewportView(jTextArea1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(441, Short.MAX_VALUE)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(574, Short.MAX_VALUE)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MisPoseciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MisPoseciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MisPoseciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MisPoseciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MisPoseciones().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
