/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package FrontendBancopoly;

import java.awt.Color;

/**
 *
 * @author phily
 */
public class SolicitudDeJugadores extends javax.swing.JDialog {

     private final Color Verde= new Color(187,221,84);
     private final Color Anaranjado= new Color(245,200,21);
     private final Color Violeta = new Color(188,40,188);
     private final Color Rosado = new Color(243,179,179);
     private final Color Azul = new Color(80,87,172);
     private final Color Rojo = new Color(227,64,64);
     
    /**
     * Creates new form SolicitudDeJugadores
     */
    public SolicitudDeJugadores(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnGroup_colores = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txt_nombreJugador = new javax.swing.JTextField();
        Rbtn_colorRosa = new javax.swing.JRadioButton();
        Rbtn_colorAzul = new javax.swing.JRadioButton();
        Rbtn_ColorAnaranjado = new javax.swing.JRadioButton();
        Rbtn_colorVerde = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        Rbtn_colorRojo = new javax.swing.JRadioButton();
        Rbtn_colorVioleta = new javax.swing.JRadioButton();
        btn_aceptar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(466, 354));
        setMinimumSize(new java.awt.Dimension(466, 354));
        setModal(true);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(200, 201, 192));
        jPanel1.setMaximumSize(new java.awt.Dimension(466, 317));
        jPanel1.setMinimumSize(new java.awt.Dimension(466, 317));

        jLabel1.setBackground(new java.awt.Color(208, 213, 185));
        jLabel1.setFont(new java.awt.Font("Sawasdee", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("<<INGRESA TUS DATOS>>");
        jLabel1.setOpaque(true);

        jLabel2.setText("Nombre :");

        txt_nombreJugador.setText(" ");

        btnGroup_colores.add(Rbtn_colorRosa);
        Rbtn_colorRosa.setText("Rosa");
        Rbtn_colorRosa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Rbtn_colorRosaActionPerformed(evt);
            }
        });

        btnGroup_colores.add(Rbtn_colorAzul);
        Rbtn_colorAzul.setText("Azul");
        Rbtn_colorAzul.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Rbtn_colorAzulActionPerformed(evt);
            }
        });

        btnGroup_colores.add(Rbtn_ColorAnaranjado);
        Rbtn_ColorAnaranjado.setText("Anaranjado");
        Rbtn_ColorAnaranjado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Rbtn_ColorAnaranjadoActionPerformed(evt);
            }
        });

        btnGroup_colores.add(Rbtn_colorVerde);
        Rbtn_colorVerde.setText("Verde");
        Rbtn_colorVerde.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Rbtn_colorVerdeActionPerformed(evt);
            }
        });

        jLabel3.setText("-> Escoge tu color de ficha:");

        btnGroup_colores.add(Rbtn_colorRojo);
        Rbtn_colorRojo.setText("Rojo");
        Rbtn_colorRojo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Rbtn_colorRojoActionPerformed(evt);
            }
        });

        btnGroup_colores.add(Rbtn_colorVioleta);
        Rbtn_colorVioleta.setText("Violeta");
        Rbtn_colorVioleta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Rbtn_colorVioletaActionPerformed(evt);
            }
        });

        btn_aceptar.setText("ACEPTAR");
        btn_aceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_aceptarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_nombreJugador, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Rbtn_colorAzul)
                            .addComponent(Rbtn_colorRosa))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 82, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Rbtn_ColorAnaranjado)
                            .addComponent(Rbtn_colorVerde))
                        .addGap(74, 74, 74)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Rbtn_colorRojo)
                            .addComponent(Rbtn_colorVioleta))
                        .addGap(36, 36, 36))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(jLabel3))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(188, 188, 188)
                        .addComponent(btn_aceptar)))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSeparator1)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jLabel1)
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_nombreJugador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(jLabel3)
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Rbtn_colorRosa)
                    .addComponent(Rbtn_ColorAnaranjado)
                    .addComponent(Rbtn_colorRojo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Rbtn_colorAzul)
                    .addComponent(Rbtn_colorVerde)
                    .addComponent(Rbtn_colorVioleta))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addComponent(btn_aceptar)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Rbtn_colorRosaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Rbtn_colorRosaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Rbtn_colorRosaActionPerformed

    private void Rbtn_ColorAnaranjadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Rbtn_ColorAnaranjadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Rbtn_ColorAnaranjadoActionPerformed

    private void btn_aceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_aceptarActionPerformed
        this.dispose();              
    }//GEN-LAST:event_btn_aceptarActionPerformed

    private void Rbtn_colorAzulActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Rbtn_colorAzulActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Rbtn_colorAzulActionPerformed

    private void Rbtn_colorVerdeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Rbtn_colorVerdeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Rbtn_colorVerdeActionPerformed

    private void Rbtn_colorRojoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Rbtn_colorRojoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Rbtn_colorRojoActionPerformed

    private void Rbtn_colorVioletaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Rbtn_colorVioletaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Rbtn_colorVioletaActionPerformed

    public void reducirYReestablecerOpciones(){
        txt_nombreJugador.setText("");//xD, aunque no concuerde con el nombre, pero con tal de no add más métodos xD, aunque no se si sea correcto
        
         if(Rbtn_colorRosa.isSelected()){
             Rbtn_colorRosa.setEnabled(false);
             Rbtn_colorRosa.setSelected(false);
        }
        if(Rbtn_colorAzul.isSelected()){
            Rbtn_colorAzul.setEnabled(false);
            Rbtn_colorAzul.setSelected(false);
        }
        if(Rbtn_ColorAnaranjado.isSelected()){
            Rbtn_ColorAnaranjado.setEnabled(false);
            Rbtn_ColorAnaranjado.setSelected(false);
        }
        if(Rbtn_colorVerde.isSelected()){
            Rbtn_colorVerde.setEnabled(false);
            Rbtn_colorVerde.setSelected(false);
        }
        if(Rbtn_colorVioleta.isSelected()){
            Rbtn_colorVioleta.setEnabled(false);
            Rbtn_colorVioleta.setSelected(false);
        }
        if(Rbtn_colorRojo.isSelected()){
            Rbtn_colorRojo.setEnabled(false);
            Rbtn_colorRojo.setSelected(false);
        }
        
    }
    
    public Color retornarColorEscogido(){
        
        if(Rbtn_colorRosa.isSelected()){
            return Rosado;
        }
        if(Rbtn_colorAzul.isSelected()){
            return Azul;
        }
        if(Rbtn_ColorAnaranjado.isSelected()){
            return Anaranjado;
        }
        if(Rbtn_colorVerde.isSelected()){
            return Verde;
        }
        if(Rbtn_colorVioleta.isSelected()){
            return Violeta;
        }
        
        return Rojo;
    }
    
    public String retornarNombreJUgador(){
        return txt_nombreJugador.getText().trim();
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton Rbtn_ColorAnaranjado;
    private javax.swing.JRadioButton Rbtn_colorAzul;
    private javax.swing.JRadioButton Rbtn_colorRojo;
    private javax.swing.JRadioButton Rbtn_colorRosa;
    private javax.swing.JRadioButton Rbtn_colorVerde;
    private javax.swing.JRadioButton Rbtn_colorVioleta;
    private javax.swing.ButtonGroup btnGroup_colores;
    private javax.swing.JButton btn_aceptar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField txt_nombreJugador;
    // End of variables declaration//GEN-END:variables
}
