/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package FrontendBancopoly;

import java.io.Serializable;

/**
 *
 * @author phily
 */
public class tarjetaCompraServicioEstacion extends javax.swing.JDialog implements Serializable{
        private boolean seCompro;
    

    /**
     * Creates new form tarjetaCompraServicioEstacion
     */
    public tarjetaCompraServicioEstacion(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel6 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        lbl_espacionombrePropiedad = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btn_comprar = new javax.swing.JButton();
        btn_dejarIr = new javax.swing.JButton();
        lbl_pagoEstancia = new javax.swing.JLabel();
        lbl_precioServicioEstacion = new javax.swing.JLabel();
        lbl_tipoPropiedad = new javax.swing.JLabel();

        jLabel6.setText("jLabel6");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(334, 405));
        setMinimumSize(new java.awt.Dimension(334, 405));
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(130, 125, 122));

        lbl_espacionombrePropiedad.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_espacionombrePropiedad.setText(" ");
        lbl_espacionombrePropiedad.setOpaque(true);

        jLabel1.setFont(new java.awt.Font("Sawasdee", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(223, 216, 216));
        jLabel1.setText("Precio $:");

        jLabel2.setForeground(new java.awt.Color(213, 201, 201));
        jLabel2.setText("-> Pago por estancia: ");

        btn_comprar.setText("Comprar");
        btn_comprar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_comprarActionPerformed(evt);
            }
        });

        btn_dejarIr.setText("Dejar ir");
        btn_dejarIr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_dejarIrActionPerformed(evt);
            }
        });

        lbl_pagoEstancia.setText(" ");

        lbl_precioServicioEstacion.setText("   ");

        lbl_tipoPropiedad.setFont(new java.awt.Font("Sawasdee", 1, 20)); // NOI18N
        lbl_tipoPropiedad.setForeground(new java.awt.Color(237, 223, 223));
        lbl_tipoPropiedad.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_tipoPropiedad.setText("jLabel3");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbl_espacionombrePropiedad, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btn_comprar)
                .addGap(18, 18, 18)
                .addComponent(btn_dejarIr)
                .addGap(24, 24, 24))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(31, 31, 31)
                                .addComponent(lbl_precioServicioEstacion, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lbl_pagoEstancia, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(107, 107, 107)
                        .addComponent(lbl_tipoPropiedad, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(43, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(lbl_tipoPropiedad, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl_espacionombrePropiedad, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(78, 78, 78)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_precioServicioEstacion, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(lbl_pagoEstancia))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 108, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_comprar)
                    .addComponent(btn_dejarIr))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_comprarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_comprarActionPerformed
        seCompro=true;
        this.dispose();
    }//GEN-LAST:event_btn_comprarActionPerformed

    private void btn_dejarIrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_dejarIrActionPerformed
        seCompro=false;
        this.dispose();
    }//GEN-LAST:event_btn_dejarIrActionPerformed

    
    public boolean retornarDecision(){
        return seCompro;
    }
    
    public void establecerDatos(String nombre, int precio, int pagoEstancia, String tipoPropiedad){
        lbl_tipoPropiedad.setText(tipoPropiedad);
        lbl_espacionombrePropiedad.setText(nombre);
        lbl_precioServicioEstacion.setText(String.valueOf(precio));
        lbl_pagoEstancia.setText(String.valueOf(pagoEstancia));
    }
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_comprar;
    private javax.swing.JButton btn_dejarIr;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbl_espacionombrePropiedad;
    private javax.swing.JLabel lbl_pagoEstancia;
    private javax.swing.JLabel lbl_precioServicioEstacion;
    private javax.swing.JLabel lbl_tipoPropiedad;
    // End of variables declaration//GEN-END:variables
}
