/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package FrontendBancopoly;

import Jugadores.Jugador;

/**
 *
 * @author phily
 */
public class TurnoDe extends javax.swing.JDialog {
    private Jugador jugadorEnTurno;
    private int avance;
    /**
     * Creates new form TurnoDe
     */
    public TurnoDe(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lbl_turno = new javax.swing.JLabel();
        lbl_descripcion = new javax.swing.JLabel();
        btn_aceptar = new javax.swing.JButton();
        lbl_numeroTurno = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(533, 225));
        setMinimumSize(new java.awt.Dimension(533, 225));
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(198, 192, 187));
        jPanel1.setMaximumSize(new java.awt.Dimension(533, 225));
        jPanel1.setMinimumSize(new java.awt.Dimension(533, 225));
        jPanel1.setPreferredSize(new java.awt.Dimension(533, 225));

        lbl_turno.setBackground(new java.awt.Color(237, 209, 182));
        lbl_turno.setFont(new java.awt.Font("Sawasdee", 1, 18)); // NOI18N
        lbl_turno.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_turno.setOpaque(true);

        lbl_descripcion.setBackground(new java.awt.Color(223, 213, 203));
        lbl_descripcion.setFont(new java.awt.Font("Sawasdee", 1, 16)); // NOI18N
        lbl_descripcion.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_descripcion.setText(" ");
        lbl_descripcion.setOpaque(true);

        btn_aceptar.setText("ACEPTAR");
        btn_aceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_aceptarActionPerformed(evt);
            }
        });

        lbl_numeroTurno.setFont(new java.awt.Font("Sawasdee", 0, 14)); // NOI18N
        lbl_numeroTurno.setText(" ");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_turno, javax.swing.GroupLayout.PREFERRED_SIZE, 471, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl_descripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 323, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_numeroTurno, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(73, 73, 73)
                        .addComponent(btn_aceptar)))
                .addContainerGap(36, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(lbl_turno, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(lbl_descripcion)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_aceptar)
                    .addComponent(lbl_numeroTurno))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_aceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_aceptarActionPerformed
        this.dispose();
        //jugadorEnTurno.avanzar(avance);
        //ya no, esto se hace en partida y este diálogo solo muestra la info, bueno, vamos a probar con la idea original, sino pues solo mostrará la info
        
    }//GEN-LAST:event_btn_aceptarActionPerformed

    public void recibirDatosParaIndicarAvance(String numeroTurno, Jugador jugador, String numeroAvance){//el jugador lo recibirá de partida, pues ella es quien contiene a todos ellos
        lbl_turno.setText(jugador.obtnerNombre()+"...");        
        lbl_numeroTurno.setText("Según lo que veo, tienes que avanzar "+numeroAvance);
        /*jugadorEnTurno=jugador;
        avance=Integer.parseInt(numeroAvance);*/
    }
    
    public void recibirDatosParaMostrarTurno(String numeroTurno, Jugador jugador){
        lbl_turno.setText(jugador.obtnerNombre()+" es tu turno...");
        lbl_descripcion.setText("-> Puedes lanzar los dados");
        lbl_numeroTurno.setText("");
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_aceptar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbl_descripcion;
    private javax.swing.JLabel lbl_numeroTurno;
    private javax.swing.JLabel lbl_turno;
    // End of variables declaration//GEN-END:variables
}
